# SPDX-License-Identifier: Apache-2.0

# =====================================
# * SUPPORTED I3C CORE CONFIGURATIONS *
# =====================================

ahb:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  DatDepth: 32
  DctDepth: 32
  FrontendBusInterface: "AHB"
  FrontendBusAddrWidth: 18
  FrontendBusDataWidth: 64
  DisableInputFF: False
  ControllerSupport: False
  TargetSupport: True

axi:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  DatDepth: 32
  DctDepth: 32
  FrontendBusInterface: "AXI"
  FrontendBusAddrWidth: 10
  FrontendBusDataWidth: 32
  FrontendBusUserWidth: 32
  FrontendBusIdWidth: 8
  FrontendBusIdFiltering: True
  NumPrivIds: 4
  DisableInputFF: False
  DisableLoopback: True
  ControllerSupport: False
  TargetSupport: True

axi_hc:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  IbiBufferDepth: 8
  DatDepth: 32
  DctDepth: 32
  FrontendBusInterface: "AXI"
  FrontendBusAddrWidth: 12
  FrontendBusDataWidth: 32
  FrontendBusUserWidth: 32
  FrontendBusIdWidth: 8
  FrontendBusIdFiltering: True
  NumPrivIds: 4
  DisableInputFF: False
  DisableLoopback: True
  ControllerSupport: True
  TargetSupport: False
  
axi_ctrl_and_target:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  TtiRxFifoDepth: 255
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  IbiBufferDepth: 8
  DatDepth: 32
  DctDepth: 32
  FrontendBusInterface: "AXI"
  FrontendBusAddrWidth: 12
  FrontendBusDataWidth: 32
  FrontendBusUserWidth: 32
  FrontendBusIdWidth: 8
  FrontendBusIdFiltering: True
  NumPrivIds: 4
  DisableInputFF: False
  DisableLoopback: True
  ControllerSupport: True
  TargetSupport: True

axi_bypass:
  CmdFifoDepth: 64
  RxFifoDepth: 64
  TxFifoDepth: 64
  RespFifoDepth: 64
  IbiFifoDepth: 64
  IbiFifoExtSize: False
  DatDepth: 32
  DctDepth: 32
  FrontendBusInterface: "AXI"
  FrontendBusAddrWidth: 12
  FrontendBusDataWidth: 32
  FrontendBusUserWidth: 32
  FrontendBusIdWidth: 8
  FrontendBusIdFiltering: True
  NumPrivIds: 4
  DisableInputFF: False
  ControllerSupport: False
  TargetSupport: True

