# SPDX-License-Identifier: Apache-2.0
"""
Generator for the AXI CSR transaction tracker SystemVerilog bind module.

Reads the compiled RDL register map (via reg_map.py dict structure) and
generates axi_csr_tracker.sv with a complete address-to-name case statement.

Called from reg_gen.py during `make config-rdl`.
"""

import logging
from pathlib import Path


# Template for the generated SV file
_SV_HEADER = """\
// SPDX-License-Identifier: Apache-2.0
//
// AUTO-GENERATED by tools/gen_axi_csr_tracker.py during `make config-rdl`.
// DO NOT EDIT MANUALLY — changes will be overwritten.
//
// AXI CSR transaction tracker for axi_adapter.
//
// Logs every completed CSR read/write with timestamp, register name, direction,
// and data value to axi_csr_transactions.log.
// Enable with +define+TRACK_FSM_TRANSITIONS at compile time.
// Usage: make ... TRACK_FSM=1
//
// Output format (one line per transaction):
//   <timestamp> | <CSR_NAME> | <READ|WRITE> | <data_hex>
// Run verification/tools/parse_axi_csr_log.py for analysis.

`ifndef SYNTHESIS
`ifndef VERILATOR

module axi_csr_tracker (
    input logic        clk_i,
    input logic        rst_ni,
    input logic        s_cpuif_wr_ack,
    input logic        s_cpuif_rd_ack,
    input logic [11:0] s_cpuif_addr,
    input logic [31:0] s_cpuif_wr_data,
    input logic [31:0] s_cpuif_rd_data
);

`ifdef TRACK_FSM_TRANSITIONS

  integer csr_log_fd;

  initial begin
    csr_log_fd = $fopen("axi_csr_transactions.log", "w");
    $fwrite(csr_log_fd, "# AXI CSR transaction log\\n");
    $fwrite(csr_log_fd, "# timestamp | csr_name | direction | data\\n");
  end

  // Address-to-name lookup (auto-generated from RDL)
  function automatic string addr_to_name(input logic [11:0] addr, input logic is_wr);
    string csr_name;
    case (addr)
"""

_SV_FOOTER = """\
      default: begin
        // DAT memory range (0x800–0xBFF)
        if (addr >= 12'h800 && addr < 12'hC00) begin
          $sformat(csr_name, "DAT[%0d]", (addr - 12'h800) >> 2);
        end else begin
          $sformat(csr_name, "UNKNOWN(0x%03h)", addr);
        end
      end
    endcase
    return csr_name;
  endfunction

  // Log on completed transactions (ack signals)
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      // Nothing to do
    end else begin
      if (s_cpuif_wr_ack) begin
        $fwrite(csr_log_fd, "%0t | %s | WRITE | 0x%08h\\n",
                $time, addr_to_name(s_cpuif_addr, 1'b1), s_cpuif_wr_data);
      end
      if (s_cpuif_rd_ack) begin
        $fwrite(csr_log_fd, "%0t | %s | READ | 0x%08h\\n",
                $time, addr_to_name(s_cpuif_addr, 1'b0), s_cpuif_rd_data);
      end
    end
  end

  final begin
    $fclose(csr_log_fd);
  end

`endif

endmodule : axi_csr_tracker

`ifdef I3C_USE_AXI
bind axi_adapter axi_csr_tracker u_axi_csr_tracker (
    .clk_i          (clk_i),
    .rst_ni         (rst_ni),
    .s_cpuif_wr_ack (s_cpuif_wr_ack),
    .s_cpuif_rd_ack (s_cpuif_rd_ack),
    .s_cpuif_addr   (s_cpuif_addr),
    .s_cpuif_wr_data(s_cpuif_wr_data),
    .s_cpuif_rd_data(s_cpuif_rd_data)
);
`endif // I3C_USE_AXI

`endif // VERILATOR
`endif // SYNTHESIS
"""


def _collect_registers(reg_map):
    """Walk reg_map dict and collect all (address, section, register_name) tuples."""
    regs = []

    def _walk(d, prefix="", base=0):
        if not isinstance(d, dict):
            return
        sa = d.get("start_addr", base)
        for k, v in d.items():
            if not isinstance(v, dict):
                continue
            # Check if this is a register (has 'offset' and at least one field with 'low')
            if "offset" in v and any(
                isinstance(fv, dict) and "low" in fv for fv in v.values() if isinstance(fv, dict)
            ):
                addr = sa + v["offset"]
                regs.append((addr, f"{prefix}{k}"))
            # Check if this is a sub-section (has nested dicts that could be registers)
            elif any(isinstance(fv, dict) for fv in v.values() if isinstance(fv, dict)):
                new_prefix = f"{prefix}{k}." if k not in ("base_addr", "start_addr", "offset") else prefix
                _walk(v, new_prefix, sa)

    _walk(reg_map)
    return regs


def _find_aliases(regs):
    """Find addresses that map to multiple register names."""
    from collections import defaultdict

    addr_to_names = defaultdict(list)
    for addr, name in regs:
        addr_to_names[addr].append(name)
    return {addr: names for addr, names in addr_to_names.items() if len(names) > 1}


def generate_axi_csr_tracker(reg_map, output_path):
    """Generate axi_csr_tracker.sv from reg_map dictionary.

    Args:
        reg_map: Register map dictionary (same structure as reg_map.py).
        output_path: Path to write the generated .sv file.
    """
    regs = _collect_registers(reg_map)
    aliases = _find_aliases(regs)

    # Filter to 12-bit address space and sort
    regs_12bit = [(addr, name) for addr, name in regs if addr <= 0xFFF]
    regs_12bit.sort(key=lambda x: (x[0], x[1]))

    # Deduplicate: for aliased addresses, pick based on R/W heuristic
    seen_addrs = set()
    case_lines = []
    current_section = None

    for addr, name in regs_12bit:
        if addr in aliases and addr in seen_addrs:
            continue  # Handled as part of alias below

        # Section comment
        parts = name.split(".")
        section = parts[0] if len(parts) > 1 else "OTHER"
        if section != current_section:
            current_section = section
            case_lines.append(f"      // {section}")

        if addr in aliases:
            names = aliases[addr]
            # Check for TX/RX pattern (R/W disambiguation)
            tx_name = next((n for n in names if "TX_" in n), None)
            rx_name = next((n for n in names if "RX_" in n), None)
            if tx_name and rx_name:
                case_lines.append(
                    f'      12\'h{addr:03X}: csr_name = is_wr ? "{tx_name}" : "{rx_name}";'
                )
            else:
                # Default: use first name
                case_lines.append(f'      12\'h{addr:03X}: csr_name = "{names[0]}";')
            seen_addrs.add(addr)
        else:
            case_lines.append(f'      12\'h{addr:03X}: csr_name = "{name}";')
            seen_addrs.add(addr)

    # Assemble full file
    sv_content = _SV_HEADER + "\n".join(case_lines) + "\n\n" + _SV_FOOTER

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write(sv_content)

    logging.info(f"Created: AXI CSR tracker {output_path} ({len(seen_addrs)} registers)")
