// SPDX-License-Identifier: Apache-2.0
//
// AUTO-GENERATED by tools/gen_axi_csr_tracker.py during `make config-rdl`.
// DO NOT EDIT MANUALLY — changes will be overwritten.
//
// AXI CSR transaction tracker for axi_adapter.
//
// Logs every completed CSR read/write with timestamp, register name, direction,
// and data value to axi_csr_transactions.log.
// Enable with +define+TRACK_FSM_TRANSITIONS at compile time.
// Usage: make ... TRACK_FSM=1
//
// Output format (one line per transaction):
//   <timestamp> | <CSR_NAME> | <READ|WRITE> | <data_hex>
// Run verification/tools/parse_axi_csr_log.py for analysis.

`ifndef SYNTHESIS
`ifndef VERILATOR

module axi_csr_tracker (
    input logic        clk_i,
    input logic        rst_ni,
    input logic        s_cpuif_wr_ack,
    input logic        s_cpuif_rd_ack,
    input logic [11:0] s_cpuif_addr,
    input logic [31:0] s_cpuif_wr_data,
    input logic [31:0] s_cpuif_rd_data
);

`ifdef TRACK_FSM_TRANSITIONS

  integer csr_log_fd;

  initial begin
    csr_log_fd = $fopen("axi_csr_transactions.log", "w");
    $fwrite(csr_log_fd, "# AXI CSR transaction log\n");
    $fwrite(csr_log_fd, "# timestamp | csr_name | direction | data\n");
  end

  // Address-to-name lookup (auto-generated from RDL)
  function automatic string addr_to_name(input logic [11:0] addr, input logic is_wr);
    string csr_name;
    case (addr)
      // I3C_EC
      12'h200: csr_name = "I3C_EC.SECFWRECOVERYIF.EXTCAP_HEADER";
      12'h204: csr_name = "I3C_EC.SECFWRECOVERYIF.PROT_CAP_0";
      12'h208: csr_name = "I3C_EC.SECFWRECOVERYIF.PROT_CAP_1";
      12'h20C: csr_name = "I3C_EC.SECFWRECOVERYIF.PROT_CAP_2";
      12'h210: csr_name = "I3C_EC.SECFWRECOVERYIF.PROT_CAP_3";
      12'h214: csr_name = "I3C_EC.SECFWRECOVERYIF.DEVICE_ID_0";
      12'h218: csr_name = "I3C_EC.SECFWRECOVERYIF.DEVICE_ID_1";
      12'h21C: csr_name = "I3C_EC.SECFWRECOVERYIF.DEVICE_ID_2";
      12'h220: csr_name = "I3C_EC.SECFWRECOVERYIF.DEVICE_ID_3";
      12'h224: csr_name = "I3C_EC.SECFWRECOVERYIF.DEVICE_ID_4";
      12'h228: csr_name = "I3C_EC.SECFWRECOVERYIF.DEVICE_ID_5";
      12'h22C: csr_name = "I3C_EC.SECFWRECOVERYIF.DEVICE_ID_RESERVED";
      12'h230: csr_name = "I3C_EC.SECFWRECOVERYIF.DEVICE_STATUS_0";
      12'h234: csr_name = "I3C_EC.SECFWRECOVERYIF.DEVICE_STATUS_1";
      12'h238: csr_name = "I3C_EC.SECFWRECOVERYIF.DEVICE_RESET";
      12'h23C: csr_name = "I3C_EC.SECFWRECOVERYIF.RECOVERY_CTRL";
      12'h240: csr_name = "I3C_EC.SECFWRECOVERYIF.RECOVERY_STATUS";
      12'h244: csr_name = "I3C_EC.SECFWRECOVERYIF.HW_STATUS";
      12'h248: csr_name = "I3C_EC.SECFWRECOVERYIF.INDIRECT_FIFO_CTRL_0";
      12'h24C: csr_name = "I3C_EC.SECFWRECOVERYIF.INDIRECT_FIFO_CTRL_1";
      12'h250: csr_name = "I3C_EC.SECFWRECOVERYIF.INDIRECT_FIFO_STATUS_0";
      12'h254: csr_name = "I3C_EC.SECFWRECOVERYIF.INDIRECT_FIFO_STATUS_1";
      12'h258: csr_name = "I3C_EC.SECFWRECOVERYIF.INDIRECT_FIFO_STATUS_2";
      12'h25C: csr_name = "I3C_EC.SECFWRECOVERYIF.INDIRECT_FIFO_STATUS_3";
      12'h260: csr_name = "I3C_EC.SECFWRECOVERYIF.INDIRECT_FIFO_STATUS_4";
      12'h264: csr_name = "I3C_EC.SECFWRECOVERYIF.INDIRECT_FIFO_RESERVED";
      12'h268: csr_name = "I3C_EC.SECFWRECOVERYIF.INDIRECT_FIFO_DATA";
      12'h300: csr_name = "I3C_EC.STDBYCTRLMODE.EXTCAP_HEADER";
      12'h304: csr_name = "I3C_EC.STDBYCTRLMODE.STBY_CR_CONTROL";
      12'h308: csr_name = "I3C_EC.STDBYCTRLMODE.STBY_CR_DEVICE_ADDR";
      12'h30C: csr_name = "I3C_EC.STDBYCTRLMODE.STBY_CR_CAPABILITIES";
      12'h310: csr_name = "I3C_EC.STDBYCTRLMODE.STBY_CR_VIRTUAL_DEVICE_CHAR";
      12'h314: csr_name = "I3C_EC.STDBYCTRLMODE.STBY_CR_STATUS";
      12'h318: csr_name = "I3C_EC.STDBYCTRLMODE.STBY_CR_DEVICE_CHAR";
      12'h31C: csr_name = "I3C_EC.STDBYCTRLMODE.STBY_CR_DEVICE_PID_LO";
      12'h320: csr_name = "I3C_EC.STDBYCTRLMODE.STBY_CR_INTR_STATUS";
      12'h324: csr_name = "I3C_EC.STDBYCTRLMODE.STBY_CR_VIRTUAL_DEVICE_PID_LO";
      12'h328: csr_name = "I3C_EC.STDBYCTRLMODE.STBY_CR_INTR_SIGNAL_ENABLE";
      12'h32C: csr_name = "I3C_EC.STDBYCTRLMODE.STBY_CR_INTR_FORCE";
      12'h330: csr_name = "I3C_EC.STDBYCTRLMODE.STBY_CR_CCC_CONFIG_GETCAPS";
      12'h334: csr_name = "I3C_EC.STDBYCTRLMODE.STBY_CR_CCC_CONFIG_RSTACT_PARAMS";
      12'h338: csr_name = "I3C_EC.STDBYCTRLMODE.STBY_CR_VIRT_DEVICE_ADDR";
      12'h33C: csr_name = "I3C_EC.STDBYCTRLMODE.STBY_CR_MWL";
      12'h340: csr_name = "I3C_EC.STDBYCTRLMODE.STBY_CR_MRL";
      12'h400: csr_name = "I3C_EC.TTI.EXTCAP_HEADER";
      12'h404: csr_name = "I3C_EC.TTI.CONTROL";
      12'h408: csr_name = "I3C_EC.TTI.STATUS";
      12'h40C: csr_name = "I3C_EC.TTI.RESET_CONTROL";
      12'h410: csr_name = "I3C_EC.TTI.QUEUE_STATUS";
      12'h414: csr_name = "I3C_EC.TTI.DESC_QUEUE_DEPTH";
      12'h418: csr_name = "I3C_EC.TTI.DATA_QUEUE_DEPTH";
      12'h41C: csr_name = "I3C_EC.TTI.IBI_QUEUE_DEPTH";
      12'h420: csr_name = "I3C_EC.TTI.INTERRUPT_STATUS";
      12'h424: csr_name = "I3C_EC.TTI.INTERRUPT_ENABLE";
      12'h428: csr_name = "I3C_EC.TTI.INTERRUPT_FORCE";
      12'h42C: csr_name = "I3C_EC.TTI.TARGET_ERR_CTRL";
      12'h430: csr_name = "I3C_EC.TTI.TARGET_ERR_INTR_STATUS";
      12'h434: csr_name = "I3C_EC.TTI.TARGET_ERR_INTR_ENABLE";
      12'h438: csr_name = "I3C_EC.TTI.TARGET_ERR_INTR_FORCE";
      12'h43C: csr_name = "I3C_EC.TTI.TARGET_ERR_CNT_TE0";
      12'h440: csr_name = "I3C_EC.TTI.TARGET_ERR_CNT_TE1";
      12'h444: csr_name = "I3C_EC.TTI.TARGET_ERR_CNT_TE2";
      12'h448: csr_name = "I3C_EC.TTI.TARGET_ERR_CNT_TE3";
      12'h44C: csr_name = "I3C_EC.TTI.TARGET_ERR_CNT_TE4";
      12'h450: csr_name = "I3C_EC.TTI.TARGET_ERR_CNT_TE5";
      12'h454: csr_name = "I3C_EC.TTI.TARGET_ERR_CNT_FRAMING";
      12'h458: csr_name = "I3C_EC.TTI.TARGET_ERR_CNT_RI_PEC";
      12'h45C: csr_name = "I3C_EC.TTI.TARGET_ERR_CNT_RI_LENGTH";
      12'h460: csr_name = "I3C_EC.TTI.TARGET_ERR_CNT_RI_READONLY";
      12'h464: csr_name = "I3C_EC.TTI.TARGET_ERR_CNT_RI_UNSUPPORTED";
      12'h468: csr_name = "I3C_EC.TTI.TARGET_ERR_CNT_RI_RX_FIFO_OVERFLOW";
      12'h46C: csr_name = "I3C_EC.TTI.TARGET_ERR_CNT_RI_INDIRECT_FIFO_OVERFLOW";
      12'h470: csr_name = "I3C_EC.TTI.RX_DESC_QUEUE_PORT";
      12'h474: csr_name = "I3C_EC.TTI.RX_DATA_PORT";
      12'h478: csr_name = "I3C_EC.TTI.TX_DESC_QUEUE_PORT";
      12'h47C: csr_name = "I3C_EC.TTI.TX_DATA_PORT";
      12'h480: csr_name = "I3C_EC.TTI.IBI_PORT";
      12'h484: csr_name = "I3C_EC.TTI.QUEUE_SIZE";
      12'h488: csr_name = "I3C_EC.TTI.IBI_QUEUE_SIZE";
      12'h48C: csr_name = "I3C_EC.TTI.QUEUE_THLD_CTRL";
      12'h490: csr_name = "I3C_EC.TTI.DATA_BUFFER_THLD_CTRL";
      12'h600: csr_name = "I3C_EC.SOCMGMTIF.EXTCAP_HEADER";
      12'h604: csr_name = "I3C_EC.SOCMGMTIF.SOC_MGMT_CONTROL";
      12'h608: csr_name = "I3C_EC.SOCMGMTIF.SOC_MGMT_STATUS";
      12'h60C: csr_name = "I3C_EC.SOCMGMTIF.REC_INTF_CFG";
      12'h610: csr_name = "I3C_EC.SOCMGMTIF.REC_INTF_REG_W1C_ACCESS";
      12'h614: csr_name = "I3C_EC.SOCMGMTIF.SOC_MGMT_RSVD_2";
      12'h618: csr_name = "I3C_EC.SOCMGMTIF.SOC_MGMT_RSVD_3";
      12'h61C: csr_name = "I3C_EC.SOCMGMTIF.SOC_PAD_CONF";
      12'h620: csr_name = "I3C_EC.SOCMGMTIF.SOC_PAD_ATTR";
      12'h624: csr_name = "I3C_EC.SOCMGMTIF.SOC_MGMT_FEATURE_2";
      12'h628: csr_name = "I3C_EC.SOCMGMTIF.SOC_MGMT_FEATURE_3";
      12'h62C: csr_name = "I3C_EC.SOCMGMTIF.T_R_REG";
      12'h630: csr_name = "I3C_EC.SOCMGMTIF.T_F_REG";
      12'h634: csr_name = "I3C_EC.SOCMGMTIF.T_SU_DAT_REG";
      12'h638: csr_name = "I3C_EC.SOCMGMTIF.T_HD_DAT_REG";
      12'h63C: csr_name = "I3C_EC.SOCMGMTIF.T_HIGH_REG";
      12'h640: csr_name = "I3C_EC.SOCMGMTIF.T_LOW_REG";
      12'h644: csr_name = "I3C_EC.SOCMGMTIF.T_HD_STA_REG";
      12'h648: csr_name = "I3C_EC.SOCMGMTIF.T_SU_STA_REG";
      12'h64C: csr_name = "I3C_EC.SOCMGMTIF.T_SU_STO_REG";
      12'h650: csr_name = "I3C_EC.SOCMGMTIF.T_FREE_REG";
      12'h654: csr_name = "I3C_EC.SOCMGMTIF.T_AVAL_REG";
      12'h658: csr_name = "I3C_EC.SOCMGMTIF.T_IDLE_REG";
      12'h65C: csr_name = "I3C_EC.SOCMGMTIF.HDR_TIMEOUT_EN_REG";
      12'h660: csr_name = "I3C_EC.SOCMGMTIF.T_HDR_TIMEOUT_REG";
      12'h6D0: csr_name = "I3C_EC.CTRLCFG.EXTCAP_HEADER";
      12'h6D4: csr_name = "I3C_EC.CTRLCFG.CONTROLLER_CONFIG";

      default: begin
        // DAT memory range (0x800–0xBFF)
        if (addr >= 12'h800 && addr < 12'hC00) begin
          $sformat(csr_name, "DAT[%0d]", (addr - 12'h800) >> 2);
        end else begin
          $sformat(csr_name, "UNKNOWN(0x%03h)", addr);
        end
      end
    endcase
    return csr_name;
  endfunction

  // Log on completed transactions (ack signals)
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      // Nothing to do
    end else begin
      if (s_cpuif_wr_ack) begin
        $fwrite(csr_log_fd, "%0t | %s | WRITE | 0x%08h\n",
                $time, addr_to_name(s_cpuif_addr, 1'b1), s_cpuif_wr_data);
      end
      if (s_cpuif_rd_ack) begin
        $fwrite(csr_log_fd, "%0t | %s | READ | 0x%08h\n",
                $time, addr_to_name(s_cpuif_addr, 1'b0), s_cpuif_rd_data);
      end
    end
  end

  final begin
    $fclose(csr_log_fd);
  end

`endif

endmodule : axi_csr_tracker

`ifdef I3C_USE_AXI
bind axi_adapter axi_csr_tracker u_axi_csr_tracker (
    .clk_i          (clk_i),
    .rst_ni         (rst_ni),
    .s_cpuif_wr_ack (s_cpuif_wr_ack),
    .s_cpuif_rd_ack (s_cpuif_rd_ack),
    .s_cpuif_addr   (s_cpuif_addr),
    .s_cpuif_wr_data(s_cpuif_wr_data),
    .s_cpuif_rd_data(s_cpuif_rd_data)
);
`endif // I3C_USE_AXI

`endif // VERILATOR
`endif // SYNTHESIS
