+incdir+${I3C_ROOT_DIR}/src
${I3C_ROOT_DIR}/src/ctrl/controller_pkg.sv
${I3C_ROOT_DIR}/src/i3c_pkg.sv
${I3C_ROOT_DIR}/src/ctrl/bus_monitor.sv
${I3C_ROOT_DIR}/src/ctrl/bus_rx_flow.sv
${I3C_ROOT_DIR}/src/ctrl/bus_tx.sv
${I3C_ROOT_DIR}/src/ctrl/bus_tx_flow.sv
${I3C_ROOT_DIR}/src/ctrl/edge_detector.sv
${I3C_ROOT_DIR}/src/ctrl/stable_high_detector.sv
${I3C_ROOT_DIR}/src/ctrl/target_reset_detector.sv
${I3C_ROOT_DIR}/src/ctrl/i3c_bus_monitor.sv
${I3C_ROOT_DIR}/src/ctrl/bus_timers.sv
${I3C_ROOT_DIR}/src/ctrl/addr_match.sv
${I3C_ROOT_DIR}/src/ctrl/descriptor_rx.sv
${I3C_ROOT_DIR}/src/ctrl/descriptor_tx.sv
${I3C_ROOT_DIR}/src/ctrl/descriptor_ibi.sv
${I3C_ROOT_DIR}/src/ctrl/i3c_target_fsm.sv
${I3C_ROOT_DIR}/src/ctrl/ccc.sv
${I3C_ROOT_DIR}/src/ctrl/controller_standby_i3c.sv
