$(CALIPTRA_ROOT)/src/caliptra_prim/rtl/caliptra_prim_assert.sv
$(CALIPTRA_ROOT)/src/caliptra_prim/rtl/caliptra_prim_assert_dummy_macros.svh
$(CALIPTRA_ROOT)/src/caliptra_prim/rtl/caliptra_prim_util_pkg.sv
$(CALIPTRA_ROOT)/src/libs/rtl/ahb_defines_pkg.sv
$(I3C_ROOT_DIR)/src/libs/axi/axi_pkg.sv
$(I3C_ROOT_DIR)/src/libs/axi/axi_if.sv
$(I3C_ROOT_DIR)/src/libs/axi/axi_sub_arb.sv
$(I3C_ROOT_DIR)/src/libs/axi/axi_sub_rd.sv
$(I3C_ROOT_DIR)/src/libs/axi/axi_sub.sv
$(I3C_ROOT_DIR)/src/libs/axi/axi_sub_wr.sv
$(I3C_ROOT_DIR)/src/libs/mem/prim_ram_1p_pkg.sv
$(I3C_ROOT_DIR)/src/libs/mem/prim_generic_ram_1p.sv
$(I3C_ROOT_DIR)/src/libs/mem/prim_ram_1p_adv.sv
$(I3C_ROOT_DIR)/src/libs/mem/prim_ram_1p.sv
$(I3C_ROOT_DIR)/src/csr/I3CCSR_pkg.sv
$(I3C_ROOT_DIR)/src/hci/hci_pkg.sv
$(I3C_ROOT_DIR)/src/ctrl/controller_pkg.sv
$(I3C_ROOT_DIR)/src/i3c_pkg.sv
$(I3C_ROOT_DIR)/src/phy/i3c_io.sv
$(I3C_ROOT_DIR)/src/phy/i3c_muxed_phy.sv
$(I3C_ROOT_DIR)/src/phy/i3c_phy_4to1_mux.sv
$(I3C_ROOT_DIR)/src/phy/i3c_phy.sv
$(I3C_ROOT_DIR)/src/csr/I3CCSR.sv
$(I3C_ROOT_DIR)/src/hci/queues/read_queue.sv
$(I3C_ROOT_DIR)/src/hci/queues/write_queue.sv
$(I3C_ROOT_DIR)/src/hci/ahb_if.sv
$(I3C_ROOT_DIR)/src/hci/axi_adapter.sv
$(I3C_ROOT_DIR)/src/hci/configuration.sv
$(I3C_ROOT_DIR)/src/hci/dxt.sv
$(I3C_ROOT_DIR)/src/hci/tti.sv
$(I3C_ROOT_DIR)/src/hci/queues.sv
$(I3C_ROOT_DIR)/src/hci/hci.sv
$(I3C_ROOT_DIR)/src/ctrl/bus_state.sv
$(I3C_ROOT_DIR)/src/ctrl/ccc.sv
$(I3C_ROOT_DIR)/src/ctrl/daa.sv
$(I3C_ROOT_DIR)/src/ctrl/i2c_controller_fsm.sv
$(I3C_ROOT_DIR)/src/ctrl/i2c_target_fsm.sv
$(I3C_ROOT_DIR)/src/ctrl/i3c_controller_fsm.sv
$(I3C_ROOT_DIR)/src/ctrl/i3c_target_fsm.sv
$(I3C_ROOT_DIR)/src/ctrl/flow_active.sv
$(I3C_ROOT_DIR)/src/ctrl/flow_standby.sv
$(I3C_ROOT_DIR)/src/ctrl/controller_active.sv
$(I3C_ROOT_DIR)/src/ctrl/controller_standby.sv
$(I3C_ROOT_DIR)/src/ctrl/controller.sv
$(I3C_ROOT_DIR)/src/i3c.sv
$(I3C_ROOT_DIR)/src/i3c_wrapper.sv
