+incdir+${CALIPTRA_ROOT}/src/libs/rtl
+incdir+${CALIPTRA_ROOT}/src/caliptra_prim/rtl
+incdir+${CALIPTRA_ROOT}/src/axi/rtl
+incdir+${I3C_ROOT_DIR}/src
+incdir+${I3C_ROOT_DIR}/src/libs
${CALIPTRA_ROOT}/src/caliptra_prim/rtl/caliptra_prim_pkg.sv
${CALIPTRA_ROOT}/src/caliptra_prim/rtl/caliptra_prim_util_pkg.sv
${CALIPTRA_ROOT}/src/caliptra_prim/rtl/caliptra_prim_count_pkg.sv
${CALIPTRA_ROOT}/src/caliptra_prim_generic/rtl/caliptra_prim_generic_flop.sv
${CALIPTRA_ROOT}/src/caliptra_prim/rtl/caliptra_prim_flop.sv
${CALIPTRA_ROOT}/src/caliptra_prim/rtl/caliptra_prim_flop_2sync.sv
${CALIPTRA_ROOT}/src/caliptra_prim/rtl/caliptra_prim_assert.sv
${CALIPTRA_ROOT}/src/caliptra_prim/rtl/caliptra_prim_assert_dummy_macros.svh
${CALIPTRA_ROOT}/src/caliptra_prim/rtl/caliptra_prim_fifo_sync_cnt.sv
${CALIPTRA_ROOT}/src/caliptra_prim/rtl/caliptra_prim_fifo_sync.sv
${CALIPTRA_ROOT}/src/libs/rtl/ahb_defines_pkg.sv
${CALIPTRA_ROOT}/src/libs/rtl/ahb_slv_sif.sv
${CALIPTRA_ROOT}/src/axi/rtl/axi_pkg.sv
${CALIPTRA_ROOT}/src/axi/rtl/axi_if.sv
${CALIPTRA_ROOT}/src/axi/rtl/axi_addr.v
${CALIPTRA_ROOT}/src/libs/rtl/skidbuffer.v
${I3C_ROOT_DIR}/src/libs/mem/prim_ram_1p_pkg.sv
${I3C_ROOT_DIR}/src/libs/mem/prim_generic_ram_1p.sv
${I3C_ROOT_DIR}/src/libs/mem/prim_ram_1p_adv.sv
${I3C_ROOT_DIR}/src/libs/mem/prim_ram_1p.sv
${I3C_ROOT_DIR}/src/csr/I3CCSR_pkg.sv
${I3C_ROOT_DIR}/src/ctrl/controller_pkg.sv
${I3C_ROOT_DIR}/src/i3c_pkg.sv
${I3C_ROOT_DIR}/src/phy/buf_pp.sv
${I3C_ROOT_DIR}/src/phy/bufs.sv
${I3C_ROOT_DIR}/src/phy/i3c_phy.sv
${I3C_ROOT_DIR}/src/csr/I3CCSR.sv
${I3C_ROOT_DIR}/src/interrupt.sv
${I3C_ROOT_DIR}/src/libs/axi_sub/i3c_axi_sub_arb.sv
${I3C_ROOT_DIR}/src/libs/axi_sub/i3c_axi_sub_rd.sv
${I3C_ROOT_DIR}/src/libs/axi_sub/i3c_axi_sub.sv
${I3C_ROOT_DIR}/src/libs/axi_sub/i3c_axi_sub_wr.sv
${I3C_ROOT_DIR}/src/hci/queues/read_queue.sv
${I3C_ROOT_DIR}/src/hci/queues/write_queue.sv
${I3C_ROOT_DIR}/src/hci/ahb_if.sv
${I3C_ROOT_DIR}/src/hci/axi_adapter.sv
${I3C_ROOT_DIR}/src/hci/dxt.sv
${I3C_ROOT_DIR}/src/hci/tti.sv
${I3C_ROOT_DIR}/src/hci/queues.sv
${I3C_ROOT_DIR}/src/hci/hci.sv
${I3C_ROOT_DIR}/src/hci/csri.sv
${I3C_ROOT_DIR}/src/ctrl/width_converter_8toN.sv
${I3C_ROOT_DIR}/src/ctrl/width_converter_Nto8.sv
${I3C_ROOT_DIR}/src/recovery/recovery_pec.sv
${I3C_ROOT_DIR}/src/recovery/recovery_receiver.sv
${I3C_ROOT_DIR}/src/recovery/recovery_transmitter.sv
${I3C_ROOT_DIR}/src/recovery/recovery_executor.sv
${I3C_ROOT_DIR}/src/recovery/recovery_handler.sv
${I3C_ROOT_DIR}/src/ctrl/bus_monitor.sv
${I3C_ROOT_DIR}/src/ctrl/ibi.sv
${I3C_ROOT_DIR}/src/ctrl/bus_tx.sv
${I3C_ROOT_DIR}/src/ctrl/bus_tx_flow.sv
${I3C_ROOT_DIR}/src/ctrl/bus_rx_flow.sv
${I3C_ROOT_DIR}/src/ctrl/bus_timers.sv
${I3C_ROOT_DIR}/src/ctrl/target_reset_detector.sv
${I3C_ROOT_DIR}/src/ctrl/i3c_bus_monitor.sv
${I3C_ROOT_DIR}/src/ctrl/ccc_entdaa.sv
${I3C_ROOT_DIR}/src/ctrl/ccc.sv
${I3C_ROOT_DIR}/src/ctrl/configuration.sv
${I3C_ROOT_DIR}/src/ctrl/edge_detector.sv
${I3C_ROOT_DIR}/src/ctrl/descriptor_rx.sv
${I3C_ROOT_DIR}/src/ctrl/descriptor_tx.sv
${I3C_ROOT_DIR}/src/ctrl/descriptor_ibi.sv
${I3C_ROOT_DIR}/src/ctrl/i2c_controller_fsm.sv
${I3C_ROOT_DIR}/src/ctrl/i2c_target_fsm.sv
${I3C_ROOT_DIR}/src/ctrl/i3c_controller_fsm.sv
${I3C_ROOT_DIR}/src/ctrl/i3c_target_fsm.sv
${I3C_ROOT_DIR}/src/ctrl/flow_active.sv
${I3C_ROOT_DIR}/src/ctrl/flow_standby_i2c.sv
${I3C_ROOT_DIR}/src/ctrl/controller_standby_i2c.sv
${I3C_ROOT_DIR}/src/ctrl/controller_standby_i3c.sv
${I3C_ROOT_DIR}/src/ctrl/controller_active.sv
${I3C_ROOT_DIR}/src/ctrl/controller_standby.sv
${I3C_ROOT_DIR}/src/ctrl/controller.sv
${I3C_ROOT_DIR}/src/ctrl/stable_high_detector.sv
${I3C_ROOT_DIR}/src/i3c.sv
${I3C_ROOT_DIR}/src/i3c_wrapper.sv
