// SPDX-License-Identifier: Apache-2.0

// The following file is autogenerated with py2svh.py tool.

`ifndef I3C_CONFIG
`define I3C_CONFIG

  `define CMD_FIFO_DEPTH    64
  `define RX_FIFO_DEPTH     64
  `define TX_FIFO_DEPTH     64
  `define RESP_FIFO_DEPTH   64
  `define IBI_FIFO_DEPTH    64
  `define IBI_FIFO_EXT_SIZE 0
  `define DAT_DEPTH         32
  `define DCT_DEPTH         32
  `define I3C_USE_AHB       1
  `define AHB_ADDR_WIDTH    12
  `define AHB_DATA_WIDTH    64

`endif  // I3C_CONFIG
