// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package I3CCSR_pkg;

    localparam I3CCSR_DATA_WIDTH = 32;
    localparam I3CCSR_MIN_ADDR_WIDTH = 12;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__HC_CONTROL__RESUME__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__HC_CONTROL__BUS_ENABLE__in_t;

    typedef struct {
        I3CCSR__I3CBase__HC_CONTROL__RESUME__in_t RESUME;
        I3CCSR__I3CBase__HC_CONTROL__BUS_ENABLE__in_t BUS_ENABLE;
    } I3CCSR__I3CBase__HC_CONTROL__in_t;

    typedef struct {
        logic [6:0] next;
        logic we;
    } I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR_VALID__in_t;

    typedef struct {
        I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR__in_t DYNAMIC_ADDR;
        I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR_VALID__in_t DYNAMIC_ADDR_VALID;
    } I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__RESET_CONTROL__SOFT_RST__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__RESET_CONTROL__CMD_QUEUE_RST__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__RESET_CONTROL__RESP_QUEUE_RST__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__RESET_CONTROL__TX_FIFO_RST__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__RESET_CONTROL__RX_FIFO_RST__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__RESET_CONTROL__IBI_QUEUE_RST__in_t;

    typedef struct {
        I3CCSR__I3CBase__RESET_CONTROL__SOFT_RST__in_t SOFT_RST;
        I3CCSR__I3CBase__RESET_CONTROL__CMD_QUEUE_RST__in_t CMD_QUEUE_RST;
        I3CCSR__I3CBase__RESET_CONTROL__RESP_QUEUE_RST__in_t RESP_QUEUE_RST;
        I3CCSR__I3CBase__RESET_CONTROL__TX_FIFO_RST__in_t TX_FIFO_RST;
        I3CCSR__I3CBase__RESET_CONTROL__RX_FIFO_RST__in_t RX_FIFO_RST;
        I3CCSR__I3CBase__RESET_CONTROL__IBI_QUEUE_RST__in_t IBI_QUEUE_RST;
    } I3CCSR__I3CBase__RESET_CONTROL__in_t;

    typedef struct {
        logic next;
    } I3CCSR__I3CBase__PRESENT_STATE__AC_CURRENT_OWN__in_t;

    typedef struct {
        I3CCSR__I3CBase__PRESENT_STATE__AC_CURRENT_OWN__in_t AC_CURRENT_OWN;
    } I3CCSR__I3CBase__PRESENT_STATE__in_t;

    typedef struct {
        logic next;
    } I3CCSR__I3CBase__INTR_STATUS__HC_INTERNAL_ERR_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__I3CBase__INTR_STATUS__HC_SEQ_CANCEL_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__I3CBase__INTR_STATUS__HC_WARN_CMD_SEQ_STALL_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__I3CBase__INTR_STATUS__HC_ERR_CMD_SEQ_TIMEOUT_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__I3CBase__INTR_STATUS__SCHED_CMD_MISSED_TICK_STAT__in_t;

    typedef struct {
        I3CCSR__I3CBase__INTR_STATUS__HC_INTERNAL_ERR_STAT__in_t HC_INTERNAL_ERR_STAT;
        I3CCSR__I3CBase__INTR_STATUS__HC_SEQ_CANCEL_STAT__in_t HC_SEQ_CANCEL_STAT;
        I3CCSR__I3CBase__INTR_STATUS__HC_WARN_CMD_SEQ_STALL_STAT__in_t HC_WARN_CMD_SEQ_STALL_STAT;
        I3CCSR__I3CBase__INTR_STATUS__HC_ERR_CMD_SEQ_TIMEOUT_STAT__in_t HC_ERR_CMD_SEQ_TIMEOUT_STAT;
        I3CCSR__I3CBase__INTR_STATUS__SCHED_CMD_MISSED_TICK_STAT__in_t SCHED_CMD_MISSED_TICK_STAT;
    } I3CCSR__I3CBase__INTR_STATUS__in_t;

    typedef struct {
        logic [4:0] next;
        logic we;
    } I3CCSR__I3CBase__DCT_SECTION_OFFSET__TABLE_INDEX__in_t;

    typedef struct {
        I3CCSR__I3CBase__DCT_SECTION_OFFSET__TABLE_INDEX__in_t TABLE_INDEX;
    } I3CCSR__I3CBase__DCT_SECTION_OFFSET__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__IBI_DATA_ABORT_MON__in_t;

    typedef struct {
        I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__IBI_DATA_ABORT_MON__in_t IBI_DATA_ABORT_MON;
    } I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__in_t;

    typedef struct {
        I3CCSR__I3CBase__HC_CONTROL__in_t HC_CONTROL;
        I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__in_t CONTROLLER_DEVICE_ADDR;
        I3CCSR__I3CBase__RESET_CONTROL__in_t RESET_CONTROL;
        I3CCSR__I3CBase__PRESENT_STATE__in_t PRESENT_STATE;
        I3CCSR__I3CBase__INTR_STATUS__in_t INTR_STATUS;
        I3CCSR__I3CBase__DCT_SECTION_OFFSET__in_t DCT_SECTION_OFFSET;
        I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__in_t IBI_DATA_ABORT_CTRL;
    } I3CCSR__I3CBase__in_t;

    typedef struct {
        logic wr_ack;
    } I3CCSR__PIOControl__COMMAND_PORT__in_t;

    typedef struct packed {
        logic RESPONSE_DATA;
        logic [30:0] _reserved_31_1;
    } I3CCSR__PIOControl__RESPONSE_PORT__fields__in_t;

    typedef struct {
        logic rd_ack;
        I3CCSR__PIOControl__RESPONSE_PORT__fields__in_t rd_data;
    } I3CCSR__PIOControl__RESPONSE_PORT__in_t;

    typedef struct packed {
        logic [31:0] RX_DATA;
    } I3CCSR__PIOControl__XFER_DATA_PORT__fields__in_t;

    typedef struct {
        logic rd_ack;
        I3CCSR__PIOControl__XFER_DATA_PORT__fields__in_t rd_data;
        logic wr_ack;
    } I3CCSR__PIOControl__XFER_DATA_PORT__in_t;

    typedef struct packed {
        logic IBI_DATA;
        logic [30:0] _reserved_31_1;
    } I3CCSR__PIOControl__IBI_PORT__fields__in_t;

    typedef struct {
        logic rd_ack;
        I3CCSR__PIOControl__IBI_PORT__fields__in_t rd_data;
    } I3CCSR__PIOControl__IBI_PORT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__TX_THLD_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__RX_THLD_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__IBI_STATUS_THLD_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__CMD_QUEUE_READY_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__RESP_READY_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__TRANSFER_ABORT_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__TRANSFER_ERR_STAT__in_t;

    typedef struct {
        I3CCSR__PIOControl__PIO_INTR_STATUS__TX_THLD_STAT__in_t TX_THLD_STAT;
        I3CCSR__PIOControl__PIO_INTR_STATUS__RX_THLD_STAT__in_t RX_THLD_STAT;
        I3CCSR__PIOControl__PIO_INTR_STATUS__IBI_STATUS_THLD_STAT__in_t IBI_STATUS_THLD_STAT;
        I3CCSR__PIOControl__PIO_INTR_STATUS__CMD_QUEUE_READY_STAT__in_t CMD_QUEUE_READY_STAT;
        I3CCSR__PIOControl__PIO_INTR_STATUS__RESP_READY_STAT__in_t RESP_READY_STAT;
        I3CCSR__PIOControl__PIO_INTR_STATUS__TRANSFER_ABORT_STAT__in_t TRANSFER_ABORT_STAT;
        I3CCSR__PIOControl__PIO_INTR_STATUS__TRANSFER_ERR_STAT__in_t TRANSFER_ERR_STAT;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__PIOControl__PIO_CONTROL__RS__in_t;

    typedef struct {
        I3CCSR__PIOControl__PIO_CONTROL__RS__in_t RS;
    } I3CCSR__PIOControl__PIO_CONTROL__in_t;

    typedef struct {
        I3CCSR__PIOControl__COMMAND_PORT__in_t COMMAND_PORT;
        I3CCSR__PIOControl__RESPONSE_PORT__in_t RESPONSE_PORT;
        I3CCSR__PIOControl__XFER_DATA_PORT__in_t XFER_DATA_PORT;
        I3CCSR__PIOControl__IBI_PORT__in_t IBI_PORT;
        I3CCSR__PIOControl__PIO_INTR_STATUS__in_t PIO_INTR_STATUS;
        I3CCSR__PIOControl__PIO_CONTROL__in_t PIO_CONTROL;
    } I3CCSR__PIOControl__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } I3CCSR__DAT__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } I3CCSR__DCT__in_t;

    typedef struct {
        I3CCSR__I3CBase__in_t I3CBase;
        I3CCSR__PIOControl__in_t PIOControl;
        I3CCSR__DAT__in_t DAT;
        I3CCSR__DCT__in_t DCT;
    } I3CCSR__in_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__HC_CONTROL__IBA_INCLUDE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__HC_CONTROL__I2C_DEV_PRESENT__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__HC_CONTROL__HOT_JOIN_CTRL__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__HC_CONTROL__HALT_ON_CMD_SEQ_TIMEOUT__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__HC_CONTROL__ABORT__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__HC_CONTROL__RESUME__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__HC_CONTROL__BUS_ENABLE__out_t;

    typedef struct {
        I3CCSR__I3CBase__HC_CONTROL__IBA_INCLUDE__out_t IBA_INCLUDE;
        I3CCSR__I3CBase__HC_CONTROL__I2C_DEV_PRESENT__out_t I2C_DEV_PRESENT;
        I3CCSR__I3CBase__HC_CONTROL__HOT_JOIN_CTRL__out_t HOT_JOIN_CTRL;
        I3CCSR__I3CBase__HC_CONTROL__HALT_ON_CMD_SEQ_TIMEOUT__out_t HALT_ON_CMD_SEQ_TIMEOUT;
        I3CCSR__I3CBase__HC_CONTROL__ABORT__out_t ABORT;
        I3CCSR__I3CBase__HC_CONTROL__RESUME__out_t RESUME;
        I3CCSR__I3CBase__HC_CONTROL__BUS_ENABLE__out_t BUS_ENABLE;
    } I3CCSR__I3CBase__HC_CONTROL__out_t;

    typedef struct {
        logic [6:0] value;
    } I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR_VALID__out_t;

    typedef struct {
        I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR__out_t DYNAMIC_ADDR;
        I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR_VALID__out_t DYNAMIC_ADDR_VALID;
    } I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__RESET_CONTROL__SOFT_RST__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__RESET_CONTROL__CMD_QUEUE_RST__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__RESET_CONTROL__RESP_QUEUE_RST__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__RESET_CONTROL__TX_FIFO_RST__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__RESET_CONTROL__RX_FIFO_RST__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__RESET_CONTROL__IBI_QUEUE_RST__out_t;

    typedef struct {
        I3CCSR__I3CBase__RESET_CONTROL__SOFT_RST__out_t SOFT_RST;
        I3CCSR__I3CBase__RESET_CONTROL__CMD_QUEUE_RST__out_t CMD_QUEUE_RST;
        I3CCSR__I3CBase__RESET_CONTROL__RESP_QUEUE_RST__out_t RESP_QUEUE_RST;
        I3CCSR__I3CBase__RESET_CONTROL__TX_FIFO_RST__out_t TX_FIFO_RST;
        I3CCSR__I3CBase__RESET_CONTROL__RX_FIFO_RST__out_t RX_FIFO_RST;
        I3CCSR__I3CBase__RESET_CONTROL__IBI_QUEUE_RST__out_t IBI_QUEUE_RST;
    } I3CCSR__I3CBase__RESET_CONTROL__out_t;

    typedef struct {
        logic intr;
    } I3CCSR__I3CBase__INTR_STATUS__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_INTERNAL_ERR_STAT_EN__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_SEQ_CANCEL_STAT_EN__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_WARN_CMD_SEQ_STALL_STAT_EN__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_ERR_CMD_SEQ_TIMEOUT_STAT_EN__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_STATUS_ENABLE__SCHED_CMD_MISSED_TICK_STAT_EN__out_t;

    typedef struct {
        I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_INTERNAL_ERR_STAT_EN__out_t HC_INTERNAL_ERR_STAT_EN;
        I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_SEQ_CANCEL_STAT_EN__out_t HC_SEQ_CANCEL_STAT_EN;
        I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_WARN_CMD_SEQ_STALL_STAT_EN__out_t HC_WARN_CMD_SEQ_STALL_STAT_EN;
        I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_ERR_CMD_SEQ_TIMEOUT_STAT_EN__out_t HC_ERR_CMD_SEQ_TIMEOUT_STAT_EN;
        I3CCSR__I3CBase__INTR_STATUS_ENABLE__SCHED_CMD_MISSED_TICK_STAT_EN__out_t SCHED_CMD_MISSED_TICK_STAT_EN;
    } I3CCSR__I3CBase__INTR_STATUS_ENABLE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_INTERNAL_ERR_SIGNAL_EN__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_SEQ_CANCEL_SIGNAL_EN__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_WARN_CMD_SEQ_STALL_SIGNAL_EN__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_ERR_CMD_SEQ_TIMEOUT_SIGNAL_EN__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__SCHED_CMD_MISSED_TICK_SIGNAL_EN__out_t;

    typedef struct {
        I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_INTERNAL_ERR_SIGNAL_EN__out_t HC_INTERNAL_ERR_SIGNAL_EN;
        I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_SEQ_CANCEL_SIGNAL_EN__out_t HC_SEQ_CANCEL_SIGNAL_EN;
        I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_WARN_CMD_SEQ_STALL_SIGNAL_EN__out_t HC_WARN_CMD_SEQ_STALL_SIGNAL_EN;
        I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_ERR_CMD_SEQ_TIMEOUT_SIGNAL_EN__out_t HC_ERR_CMD_SEQ_TIMEOUT_SIGNAL_EN;
        I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__SCHED_CMD_MISSED_TICK_SIGNAL_EN__out_t SCHED_CMD_MISSED_TICK_SIGNAL_EN;
    } I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_FORCE__HC_INTERNAL_ERR_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_FORCE__HC_SEQ_CANCEL_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_FORCE__HC_WARN_CMD_SEQ_STALL_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_FORCE__HC_ERR_CMD_SEQ_TIMEOUT_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_FORCE__SCHED_CMD_MISSED_TICK_FORCE__out_t;

    typedef struct {
        I3CCSR__I3CBase__INTR_FORCE__HC_INTERNAL_ERR_FORCE__out_t HC_INTERNAL_ERR_FORCE;
        I3CCSR__I3CBase__INTR_FORCE__HC_SEQ_CANCEL_FORCE__out_t HC_SEQ_CANCEL_FORCE;
        I3CCSR__I3CBase__INTR_FORCE__HC_WARN_CMD_SEQ_STALL_FORCE__out_t HC_WARN_CMD_SEQ_STALL_FORCE;
        I3CCSR__I3CBase__INTR_FORCE__HC_ERR_CMD_SEQ_TIMEOUT_FORCE__out_t HC_ERR_CMD_SEQ_TIMEOUT_FORCE;
        I3CCSR__I3CBase__INTR_FORCE__SCHED_CMD_MISSED_TICK_FORCE__out_t SCHED_CMD_MISSED_TICK_FORCE;
    } I3CCSR__I3CBase__INTR_FORCE__out_t;

    typedef struct {
        logic [4:0] value;
    } I3CCSR__I3CBase__DCT_SECTION_OFFSET__TABLE_INDEX__out_t;

    typedef struct {
        I3CCSR__I3CBase__DCT_SECTION_OFFSET__TABLE_INDEX__out_t TABLE_INDEX;
    } I3CCSR__I3CBase__DCT_SECTION_OFFSET__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_HJ_REJECTED__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_CRR_REJECTED__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_IBI_REJECTED__out_t;

    typedef struct {
        I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_HJ_REJECTED__out_t NOTIFY_HJ_REJECTED;
        I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_CRR_REJECTED__out_t NOTIFY_CRR_REJECTED;
        I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_IBI_REJECTED__out_t NOTIFY_IBI_REJECTED;
    } I3CCSR__I3CBase__IBI_NOTIFY_CTRL__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__MATCH_IBI_ID__out_t;

    typedef struct {
        logic [1:0] value;
    } I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__AFTER_N_CHUNKS__out_t;

    typedef struct {
        logic [2:0] value;
    } I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__MATCH_STATUS_TYPE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__IBI_DATA_ABORT_MON__out_t;

    typedef struct {
        I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__MATCH_IBI_ID__out_t MATCH_IBI_ID;
        I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__AFTER_N_CHUNKS__out_t AFTER_N_CHUNKS;
        I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__MATCH_STATUS_TYPE__out_t MATCH_STATUS_TYPE;
        I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__IBI_DATA_ABORT_MON__out_t IBI_DATA_ABORT_MON;
    } I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__DEV_CTX_BASE_LO__BASE_LO__out_t;

    typedef struct {
        I3CCSR__I3CBase__DEV_CTX_BASE_LO__BASE_LO__out_t BASE_LO;
    } I3CCSR__I3CBase__DEV_CTX_BASE_LO__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__DEV_CTX_BASE_HI__BASE_HI__out_t;

    typedef struct {
        I3CCSR__I3CBase__DEV_CTX_BASE_HI__BASE_HI__out_t BASE_HI;
    } I3CCSR__I3CBase__DEV_CTX_BASE_HI__out_t;

    typedef struct {
        I3CCSR__I3CBase__HC_CONTROL__out_t HC_CONTROL;
        I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__out_t CONTROLLER_DEVICE_ADDR;
        I3CCSR__I3CBase__RESET_CONTROL__out_t RESET_CONTROL;
        I3CCSR__I3CBase__INTR_STATUS__out_t INTR_STATUS;
        I3CCSR__I3CBase__INTR_STATUS_ENABLE__out_t INTR_STATUS_ENABLE;
        I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__out_t INTR_SIGNAL_ENABLE;
        I3CCSR__I3CBase__INTR_FORCE__out_t INTR_FORCE;
        I3CCSR__I3CBase__DCT_SECTION_OFFSET__out_t DCT_SECTION_OFFSET;
        I3CCSR__I3CBase__IBI_NOTIFY_CTRL__out_t IBI_NOTIFY_CTRL;
        I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__out_t IBI_DATA_ABORT_CTRL;
        I3CCSR__I3CBase__DEV_CTX_BASE_LO__out_t DEV_CTX_BASE_LO;
        I3CCSR__I3CBase__DEV_CTX_BASE_HI__out_t DEV_CTX_BASE_HI;
    } I3CCSR__I3CBase__out_t;

    typedef struct packed {
        logic COMMAND_DATA;
        logic [30:0] _reserved_31_1;
    } I3CCSR__PIOControl__COMMAND_PORT__fields__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
        I3CCSR__PIOControl__COMMAND_PORT__fields__out_t wr_data;
        I3CCSR__PIOControl__COMMAND_PORT__fields__out_t wr_biten;
    } I3CCSR__PIOControl__COMMAND_PORT__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } I3CCSR__PIOControl__RESPONSE_PORT__out_t;

    typedef struct packed {
        logic [31:0] TX_DATA;
    } I3CCSR__PIOControl__XFER_DATA_PORT__fields__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
        I3CCSR__PIOControl__XFER_DATA_PORT__fields__out_t wr_data;
        I3CCSR__PIOControl__XFER_DATA_PORT__fields__out_t wr_biten;
    } I3CCSR__PIOControl__XFER_DATA_PORT__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } I3CCSR__PIOControl__IBI_PORT__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__PIOControl__QUEUE_THLD_CTRL__CMD_EMPTY_BUF_THLD__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__PIOControl__QUEUE_THLD_CTRL__RESP_BUF_THLD__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__PIOControl__QUEUE_THLD_CTRL__IBI_DATA_SEGMENT_SIZE__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__PIOControl__QUEUE_THLD_CTRL__IBI_STATUS_THLD__out_t;

    typedef struct {
        I3CCSR__PIOControl__QUEUE_THLD_CTRL__CMD_EMPTY_BUF_THLD__out_t CMD_EMPTY_BUF_THLD;
        I3CCSR__PIOControl__QUEUE_THLD_CTRL__RESP_BUF_THLD__out_t RESP_BUF_THLD;
        I3CCSR__PIOControl__QUEUE_THLD_CTRL__IBI_DATA_SEGMENT_SIZE__out_t IBI_DATA_SEGMENT_SIZE;
        I3CCSR__PIOControl__QUEUE_THLD_CTRL__IBI_STATUS_THLD__out_t IBI_STATUS_THLD;
    } I3CCSR__PIOControl__QUEUE_THLD_CTRL__out_t;

    typedef struct {
        logic [2:0] value;
    } I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__TX_BUF_THLD__out_t;

    typedef struct {
        logic [2:0] value;
    } I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__RX_BUF_THLD__out_t;

    typedef struct {
        logic [2:0] value;
    } I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__TX_START_THLD__out_t;

    typedef struct {
        logic [2:0] value;
    } I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__RX_START_THLD__out_t;

    typedef struct {
        I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__TX_BUF_THLD__out_t TX_BUF_THLD;
        I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__RX_BUF_THLD__out_t RX_BUF_THLD;
        I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__TX_START_THLD__out_t TX_START_THLD;
        I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__RX_START_THLD__out_t RX_START_THLD;
    } I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__out_t;

    typedef struct {
        logic intr;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_INTR_FORCE__TX_THLD_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_INTR_FORCE__RX_THLD_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_INTR_FORCE__IBI_THLD_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_INTR_FORCE__CMD_QUEUE_READY_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_INTR_FORCE__RESP_READY_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_INTR_FORCE__TRANSFER_ABORT_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_INTR_FORCE__TRANSFER_ERR_FORCE__out_t;

    typedef struct {
        I3CCSR__PIOControl__PIO_INTR_FORCE__TX_THLD_FORCE__out_t TX_THLD_FORCE;
        I3CCSR__PIOControl__PIO_INTR_FORCE__RX_THLD_FORCE__out_t RX_THLD_FORCE;
        I3CCSR__PIOControl__PIO_INTR_FORCE__IBI_THLD_FORCE__out_t IBI_THLD_FORCE;
        I3CCSR__PIOControl__PIO_INTR_FORCE__CMD_QUEUE_READY_FORCE__out_t CMD_QUEUE_READY_FORCE;
        I3CCSR__PIOControl__PIO_INTR_FORCE__RESP_READY_FORCE__out_t RESP_READY_FORCE;
        I3CCSR__PIOControl__PIO_INTR_FORCE__TRANSFER_ABORT_FORCE__out_t TRANSFER_ABORT_FORCE;
        I3CCSR__PIOControl__PIO_INTR_FORCE__TRANSFER_ERR_FORCE__out_t TRANSFER_ERR_FORCE;
    } I3CCSR__PIOControl__PIO_INTR_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_CONTROL__ENABLE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_CONTROL__ABORT__out_t;

    typedef struct {
        I3CCSR__PIOControl__PIO_CONTROL__ENABLE__out_t ENABLE;
        I3CCSR__PIOControl__PIO_CONTROL__ABORT__out_t ABORT;
    } I3CCSR__PIOControl__PIO_CONTROL__out_t;

    typedef struct {
        I3CCSR__PIOControl__COMMAND_PORT__out_t COMMAND_PORT;
        I3CCSR__PIOControl__RESPONSE_PORT__out_t RESPONSE_PORT;
        I3CCSR__PIOControl__XFER_DATA_PORT__out_t XFER_DATA_PORT;
        I3CCSR__PIOControl__IBI_PORT__out_t IBI_PORT;
        I3CCSR__PIOControl__QUEUE_THLD_CTRL__out_t QUEUE_THLD_CTRL;
        I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__out_t DATA_BUFFER_THLD_CTRL;
        I3CCSR__PIOControl__PIO_INTR_STATUS__out_t PIO_INTR_STATUS;
        I3CCSR__PIOControl__PIO_INTR_FORCE__out_t PIO_INTR_FORCE;
        I3CCSR__PIOControl__PIO_CONTROL__out_t PIO_CONTROL;
    } I3CCSR__PIOControl__out_t;

    typedef struct {
        logic req;
        logic [9:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } I3CCSR__DAT__out_t;

    typedef struct {
        logic req;
        logic [10:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } I3CCSR__DCT__out_t;

    typedef struct {
        I3CCSR__I3CBase__out_t I3CBase;
        I3CCSR__PIOControl__out_t PIOControl;
        I3CCSR__DAT__out_t DAT;
        I3CCSR__DCT__out_t DCT;
    } I3CCSR__out_t;
endpackage
