// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package I3CCSR_pkg;

    localparam I3CCSR_DATA_WIDTH = 32;
    localparam I3CCSR_MIN_ADDR_WIDTH = 12;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__HC_CONTROL__RESUME__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__HC_CONTROL__BUS_ENABLE__in_t;

    typedef struct {
        I3CCSR__I3CBase__HC_CONTROL__RESUME__in_t RESUME;
        I3CCSR__I3CBase__HC_CONTROL__BUS_ENABLE__in_t BUS_ENABLE;
    } I3CCSR__I3CBase__HC_CONTROL__in_t;

    typedef struct {
        logic [6:0] next;
        logic we;
    } I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR_VALID__in_t;

    typedef struct {
        I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR__in_t DYNAMIC_ADDR;
        I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR_VALID__in_t DYNAMIC_ADDR_VALID;
    } I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__RESET_CONTROL__SOFT_RST__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__RESET_CONTROL__CMD_QUEUE_RST__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__RESET_CONTROL__RESP_QUEUE_RST__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__RESET_CONTROL__TX_FIFO_RST__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__RESET_CONTROL__RX_FIFO_RST__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__RESET_CONTROL__IBI_QUEUE_RST__in_t;

    typedef struct {
        I3CCSR__I3CBase__RESET_CONTROL__SOFT_RST__in_t SOFT_RST;
        I3CCSR__I3CBase__RESET_CONTROL__CMD_QUEUE_RST__in_t CMD_QUEUE_RST;
        I3CCSR__I3CBase__RESET_CONTROL__RESP_QUEUE_RST__in_t RESP_QUEUE_RST;
        I3CCSR__I3CBase__RESET_CONTROL__TX_FIFO_RST__in_t TX_FIFO_RST;
        I3CCSR__I3CBase__RESET_CONTROL__RX_FIFO_RST__in_t RX_FIFO_RST;
        I3CCSR__I3CBase__RESET_CONTROL__IBI_QUEUE_RST__in_t IBI_QUEUE_RST;
    } I3CCSR__I3CBase__RESET_CONTROL__in_t;

    typedef struct {
        logic next;
    } I3CCSR__I3CBase__PRESENT_STATE__AC_CURRENT_OWN__in_t;

    typedef struct {
        I3CCSR__I3CBase__PRESENT_STATE__AC_CURRENT_OWN__in_t AC_CURRENT_OWN;
    } I3CCSR__I3CBase__PRESENT_STATE__in_t;

    typedef struct {
        logic next;
    } I3CCSR__I3CBase__INTR_STATUS__HC_INTERNAL_ERR_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__I3CBase__INTR_STATUS__HC_SEQ_CANCEL_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__I3CBase__INTR_STATUS__HC_WARN_CMD_SEQ_STALL_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__I3CBase__INTR_STATUS__HC_ERR_CMD_SEQ_TIMEOUT_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__I3CBase__INTR_STATUS__SCHED_CMD_MISSED_TICK_STAT__in_t;

    typedef struct {
        I3CCSR__I3CBase__INTR_STATUS__HC_INTERNAL_ERR_STAT__in_t HC_INTERNAL_ERR_STAT;
        I3CCSR__I3CBase__INTR_STATUS__HC_SEQ_CANCEL_STAT__in_t HC_SEQ_CANCEL_STAT;
        I3CCSR__I3CBase__INTR_STATUS__HC_WARN_CMD_SEQ_STALL_STAT__in_t HC_WARN_CMD_SEQ_STALL_STAT;
        I3CCSR__I3CBase__INTR_STATUS__HC_ERR_CMD_SEQ_TIMEOUT_STAT__in_t HC_ERR_CMD_SEQ_TIMEOUT_STAT;
        I3CCSR__I3CBase__INTR_STATUS__SCHED_CMD_MISSED_TICK_STAT__in_t SCHED_CMD_MISSED_TICK_STAT;
    } I3CCSR__I3CBase__INTR_STATUS__in_t;

    typedef struct {
        logic [4:0] next;
        logic we;
    } I3CCSR__I3CBase__DCT_SECTION_OFFSET__TABLE_INDEX__in_t;

    typedef struct {
        I3CCSR__I3CBase__DCT_SECTION_OFFSET__TABLE_INDEX__in_t TABLE_INDEX;
    } I3CCSR__I3CBase__DCT_SECTION_OFFSET__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__IBI_DATA_ABORT_MON__in_t;

    typedef struct {
        I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__IBI_DATA_ABORT_MON__in_t IBI_DATA_ABORT_MON;
    } I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__in_t;

    typedef struct {
        I3CCSR__I3CBase__HC_CONTROL__in_t HC_CONTROL;
        I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__in_t CONTROLLER_DEVICE_ADDR;
        I3CCSR__I3CBase__RESET_CONTROL__in_t RESET_CONTROL;
        I3CCSR__I3CBase__PRESENT_STATE__in_t PRESENT_STATE;
        I3CCSR__I3CBase__INTR_STATUS__in_t INTR_STATUS;
        I3CCSR__I3CBase__DCT_SECTION_OFFSET__in_t DCT_SECTION_OFFSET;
        I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__in_t IBI_DATA_ABORT_CTRL;
    } I3CCSR__I3CBase__in_t;

    typedef struct {
        logic wr_ack;
    } I3CCSR__PIOControl__COMMAND_PORT__in_t;

    typedef struct packed {
        logic RESPONSE_DATA;
        logic [30:0] _reserved_31_1;
    } I3CCSR__PIOControl__RESPONSE_PORT__fields__in_t;

    typedef struct {
        logic rd_ack;
        I3CCSR__PIOControl__RESPONSE_PORT__fields__in_t rd_data;
    } I3CCSR__PIOControl__RESPONSE_PORT__in_t;

    typedef struct packed {
        logic [31:0] RX_DATA;
    } I3CCSR__PIOControl__XFER_DATA_PORT__fields__in_t;

    typedef struct {
        logic rd_ack;
        I3CCSR__PIOControl__XFER_DATA_PORT__fields__in_t rd_data;
        logic wr_ack;
    } I3CCSR__PIOControl__XFER_DATA_PORT__in_t;

    typedef struct packed {
        logic IBI_DATA;
        logic [30:0] _reserved_31_1;
    } I3CCSR__PIOControl__IBI_PORT__fields__in_t;

    typedef struct {
        logic rd_ack;
        I3CCSR__PIOControl__IBI_PORT__fields__in_t rd_data;
    } I3CCSR__PIOControl__IBI_PORT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__TX_THLD_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__RX_THLD_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__IBI_STATUS_THLD_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__CMD_QUEUE_READY_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__RESP_READY_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__TRANSFER_ABORT_STAT__in_t;

    typedef struct {
        logic next;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__TRANSFER_ERR_STAT__in_t;

    typedef struct {
        I3CCSR__PIOControl__PIO_INTR_STATUS__TX_THLD_STAT__in_t TX_THLD_STAT;
        I3CCSR__PIOControl__PIO_INTR_STATUS__RX_THLD_STAT__in_t RX_THLD_STAT;
        I3CCSR__PIOControl__PIO_INTR_STATUS__IBI_STATUS_THLD_STAT__in_t IBI_STATUS_THLD_STAT;
        I3CCSR__PIOControl__PIO_INTR_STATUS__CMD_QUEUE_READY_STAT__in_t CMD_QUEUE_READY_STAT;
        I3CCSR__PIOControl__PIO_INTR_STATUS__RESP_READY_STAT__in_t RESP_READY_STAT;
        I3CCSR__PIOControl__PIO_INTR_STATUS__TRANSFER_ABORT_STAT__in_t TRANSFER_ABORT_STAT;
        I3CCSR__PIOControl__PIO_INTR_STATUS__TRANSFER_ERR_STAT__in_t TRANSFER_ERR_STAT;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__in_t;

    typedef struct {
        logic next;
        logic we;
    } I3CCSR__PIOControl__PIO_CONTROL__RS__in_t;

    typedef struct {
        I3CCSR__PIOControl__PIO_CONTROL__RS__in_t RS;
    } I3CCSR__PIOControl__PIO_CONTROL__in_t;

    typedef struct {
        I3CCSR__PIOControl__COMMAND_PORT__in_t COMMAND_PORT;
        I3CCSR__PIOControl__RESPONSE_PORT__in_t RESPONSE_PORT;
        I3CCSR__PIOControl__XFER_DATA_PORT__in_t XFER_DATA_PORT;
        I3CCSR__PIOControl__IBI_PORT__in_t IBI_PORT;
        I3CCSR__PIOControl__PIO_INTR_STATUS__in_t PIO_INTR_STATUS;
        I3CCSR__PIOControl__PIO_CONTROL__in_t PIO_CONTROL;
    } I3CCSR__PIOControl__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_0__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_0__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_0__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_1__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_1__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_1__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_2__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_2__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_2__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_3__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_3__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_3__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_0__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_0__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_0__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_1__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_1__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_1__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_2__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_2__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_2__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_3__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_3__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_3__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_4__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_4__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_4__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_5__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_5__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_5__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_6__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_6__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_6__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_STATUS_0__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_STATUS_0__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_STATUS_0__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_STATUS_1__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_STATUS_1__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_STATUS_1__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_RESET__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_RESET__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_RESET__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__RECOVERY_CTRL__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__RECOVERY_CTRL__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__RECOVERY_CTRL__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__RECOVERY_STATUS__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__RECOVERY_STATUS__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__RECOVERY_STATUS__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__HW_STATUS__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__HW_STATUS__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__HW_STATUS__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_CTRL_0__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_CTRL_0__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_CTRL_0__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_CTRL_1__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_CTRL_1__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_CTRL_1__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_0__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_0__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_0__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_1__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_1__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_1__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_2__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_2__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_2__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_3__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_3__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_3__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_4__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_4__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_4__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_5__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_5__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_5__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_DATA__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_DATA__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_DATA__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_0__in_t PROT_CAP_0;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_1__in_t PROT_CAP_1;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_2__in_t PROT_CAP_2;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_3__in_t PROT_CAP_3;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_0__in_t DEVICE_ID_0;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_1__in_t DEVICE_ID_1;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_2__in_t DEVICE_ID_2;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_3__in_t DEVICE_ID_3;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_4__in_t DEVICE_ID_4;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_5__in_t DEVICE_ID_5;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_6__in_t DEVICE_ID_6;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_STATUS_0__in_t DEVICE_STATUS_0;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_STATUS_1__in_t DEVICE_STATUS_1;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_RESET__in_t DEVICE_RESET;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__RECOVERY_CTRL__in_t RECOVERY_CTRL;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__RECOVERY_STATUS__in_t RECOVERY_STATUS;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__HW_STATUS__in_t HW_STATUS;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_CTRL_0__in_t INDIRECT_FIFO_CTRL_0;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_CTRL_1__in_t INDIRECT_FIFO_CTRL_1;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_0__in_t INDIRECT_FIFO_STATUS_0;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_1__in_t INDIRECT_FIFO_STATUS_1;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_2__in_t INDIRECT_FIFO_STATUS_2;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_3__in_t INDIRECT_FIFO_STATUS_3;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_4__in_t INDIRECT_FIFO_STATUS_4;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_5__in_t INDIRECT_FIFO_STATUS_5;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_DATA__in_t INDIRECT_FIFO_DATA;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_CONTROL__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_CONTROL__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_CONTROL__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_STATUS__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_STATUS__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_STATUS__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_STATUS__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_STATUS__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_STATUS__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_ENABLE__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_ENABLE__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_ENABLE__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_FORCE__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_FORCE__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_FORCE__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_RX_DESCRIPTOR_QUEUE_PORT__TTI_RX_DESCRIPTOR__in_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_RX_DESCRIPTOR_QUEUE_PORT__TTI_RX_DESCRIPTOR__in_t TTI_RX_DESCRIPTOR;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_RX_DESCRIPTOR_QUEUE_PORT__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_RX_DATA_PORT__TTI_RX_DATA__in_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_RX_DATA_PORT__TTI_RX_DATA__in_t TTI_RX_DATA;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_RX_DATA_PORT__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_TX_DESCRIPTOR_QUEUE_PORT__TTI_TX_DESCRIPTOR__in_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_TX_DESCRIPTOR_QUEUE_PORT__TTI_TX_DESCRIPTOR__in_t TTI_TX_DESCRIPTOR;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_TX_DESCRIPTOR_QUEUE_PORT__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_TX_DATA_PORT__TTI_TX_DATA__in_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_TX_DATA_PORT__TTI_TX_DATA__in_t TTI_TX_DATA;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_TX_DATA_PORT__in_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_CONTROL__in_t TTI_CONTROL;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_STATUS__in_t TTI_STATUS;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_STATUS__in_t TTI_INTERRUPT_STATUS;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_ENABLE__in_t TTI_INTERRUPT_ENABLE;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_FORCE__in_t TTI_INTERRUPT_FORCE;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_RX_DESCRIPTOR_QUEUE_PORT__in_t TTI_RX_DESCRIPTOR_QUEUE_PORT;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_RX_DATA_PORT__in_t TTI_RX_DATA_PORT;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_TX_DESCRIPTOR_QUEUE_PORT__in_t TTI_TX_DESCRIPTOR_QUEUE_PORT;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_TX_DATA_PORT__in_t TTI_TX_DATA_PORT;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__PLACE_HOLDER_1__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__PLACE_HOLDER_1__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__PLACE_HOLDER_1__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__PLACE_HOLDER_1__in_t PLACE_HOLDER_1;
    } I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__in_t;

    typedef struct {
        logic [31:0] next;
    } I3CCSR__I3C_EC__ControllerConfigRegisters__PLACE_HOLDER_1__PLACEHOLDER__in_t;

    typedef struct {
        I3CCSR__I3C_EC__ControllerConfigRegisters__PLACE_HOLDER_1__PLACEHOLDER__in_t PLACEHOLDER;
    } I3CCSR__I3C_EC__ControllerConfigRegisters__PLACE_HOLDER_1__in_t;

    typedef struct {
        I3CCSR__I3C_EC__ControllerConfigRegisters__PLACE_HOLDER_1__in_t PLACE_HOLDER_1;
    } I3CCSR__I3C_EC__ControllerConfigRegisters__in_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__in_t SecureFirmwareRecoveryInterfaceRegisters;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__in_t TargetTransactionInterfaceRegisters;
        I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__in_t SoCManagementInterfaceRegisters;
        I3CCSR__I3C_EC__ControllerConfigRegisters__in_t ControllerConfigRegisters;
    } I3CCSR__I3C_EC__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } I3CCSR__DAT__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } I3CCSR__DCT__in_t;

    typedef struct {
        logic rst_ni;
        I3CCSR__I3CBase__in_t I3CBase;
        I3CCSR__PIOControl__in_t PIOControl;
        I3CCSR__I3C_EC__in_t I3C_EC;
        I3CCSR__DAT__in_t DAT;
        I3CCSR__DCT__in_t DCT;
    } I3CCSR__in_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__HC_CONTROL__IBA_INCLUDE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__HC_CONTROL__I2C_DEV_PRESENT__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__HC_CONTROL__HOT_JOIN_CTRL__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__HC_CONTROL__HALT_ON_CMD_SEQ_TIMEOUT__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__HC_CONTROL__ABORT__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__HC_CONTROL__RESUME__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__HC_CONTROL__BUS_ENABLE__out_t;

    typedef struct {
        I3CCSR__I3CBase__HC_CONTROL__IBA_INCLUDE__out_t IBA_INCLUDE;
        I3CCSR__I3CBase__HC_CONTROL__I2C_DEV_PRESENT__out_t I2C_DEV_PRESENT;
        I3CCSR__I3CBase__HC_CONTROL__HOT_JOIN_CTRL__out_t HOT_JOIN_CTRL;
        I3CCSR__I3CBase__HC_CONTROL__HALT_ON_CMD_SEQ_TIMEOUT__out_t HALT_ON_CMD_SEQ_TIMEOUT;
        I3CCSR__I3CBase__HC_CONTROL__ABORT__out_t ABORT;
        I3CCSR__I3CBase__HC_CONTROL__RESUME__out_t RESUME;
        I3CCSR__I3CBase__HC_CONTROL__BUS_ENABLE__out_t BUS_ENABLE;
    } I3CCSR__I3CBase__HC_CONTROL__out_t;

    typedef struct {
        logic [6:0] value;
    } I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR_VALID__out_t;

    typedef struct {
        I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR__out_t DYNAMIC_ADDR;
        I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__DYNAMIC_ADDR_VALID__out_t DYNAMIC_ADDR_VALID;
    } I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__RESET_CONTROL__SOFT_RST__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__RESET_CONTROL__CMD_QUEUE_RST__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__RESET_CONTROL__RESP_QUEUE_RST__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__RESET_CONTROL__TX_FIFO_RST__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__RESET_CONTROL__RX_FIFO_RST__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__RESET_CONTROL__IBI_QUEUE_RST__out_t;

    typedef struct {
        I3CCSR__I3CBase__RESET_CONTROL__SOFT_RST__out_t SOFT_RST;
        I3CCSR__I3CBase__RESET_CONTROL__CMD_QUEUE_RST__out_t CMD_QUEUE_RST;
        I3CCSR__I3CBase__RESET_CONTROL__RESP_QUEUE_RST__out_t RESP_QUEUE_RST;
        I3CCSR__I3CBase__RESET_CONTROL__TX_FIFO_RST__out_t TX_FIFO_RST;
        I3CCSR__I3CBase__RESET_CONTROL__RX_FIFO_RST__out_t RX_FIFO_RST;
        I3CCSR__I3CBase__RESET_CONTROL__IBI_QUEUE_RST__out_t IBI_QUEUE_RST;
    } I3CCSR__I3CBase__RESET_CONTROL__out_t;

    typedef struct {
        logic intr;
    } I3CCSR__I3CBase__INTR_STATUS__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_INTERNAL_ERR_STAT_EN__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_SEQ_CANCEL_STAT_EN__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_WARN_CMD_SEQ_STALL_STAT_EN__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_ERR_CMD_SEQ_TIMEOUT_STAT_EN__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_STATUS_ENABLE__SCHED_CMD_MISSED_TICK_STAT_EN__out_t;

    typedef struct {
        I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_INTERNAL_ERR_STAT_EN__out_t HC_INTERNAL_ERR_STAT_EN;
        I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_SEQ_CANCEL_STAT_EN__out_t HC_SEQ_CANCEL_STAT_EN;
        I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_WARN_CMD_SEQ_STALL_STAT_EN__out_t HC_WARN_CMD_SEQ_STALL_STAT_EN;
        I3CCSR__I3CBase__INTR_STATUS_ENABLE__HC_ERR_CMD_SEQ_TIMEOUT_STAT_EN__out_t HC_ERR_CMD_SEQ_TIMEOUT_STAT_EN;
        I3CCSR__I3CBase__INTR_STATUS_ENABLE__SCHED_CMD_MISSED_TICK_STAT_EN__out_t SCHED_CMD_MISSED_TICK_STAT_EN;
    } I3CCSR__I3CBase__INTR_STATUS_ENABLE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_INTERNAL_ERR_SIGNAL_EN__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_SEQ_CANCEL_SIGNAL_EN__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_WARN_CMD_SEQ_STALL_SIGNAL_EN__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_ERR_CMD_SEQ_TIMEOUT_SIGNAL_EN__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__SCHED_CMD_MISSED_TICK_SIGNAL_EN__out_t;

    typedef struct {
        I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_INTERNAL_ERR_SIGNAL_EN__out_t HC_INTERNAL_ERR_SIGNAL_EN;
        I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_SEQ_CANCEL_SIGNAL_EN__out_t HC_SEQ_CANCEL_SIGNAL_EN;
        I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_WARN_CMD_SEQ_STALL_SIGNAL_EN__out_t HC_WARN_CMD_SEQ_STALL_SIGNAL_EN;
        I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__HC_ERR_CMD_SEQ_TIMEOUT_SIGNAL_EN__out_t HC_ERR_CMD_SEQ_TIMEOUT_SIGNAL_EN;
        I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__SCHED_CMD_MISSED_TICK_SIGNAL_EN__out_t SCHED_CMD_MISSED_TICK_SIGNAL_EN;
    } I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_FORCE__HC_INTERNAL_ERR_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_FORCE__HC_SEQ_CANCEL_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_FORCE__HC_WARN_CMD_SEQ_STALL_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_FORCE__HC_ERR_CMD_SEQ_TIMEOUT_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__INTR_FORCE__SCHED_CMD_MISSED_TICK_FORCE__out_t;

    typedef struct {
        I3CCSR__I3CBase__INTR_FORCE__HC_INTERNAL_ERR_FORCE__out_t HC_INTERNAL_ERR_FORCE;
        I3CCSR__I3CBase__INTR_FORCE__HC_SEQ_CANCEL_FORCE__out_t HC_SEQ_CANCEL_FORCE;
        I3CCSR__I3CBase__INTR_FORCE__HC_WARN_CMD_SEQ_STALL_FORCE__out_t HC_WARN_CMD_SEQ_STALL_FORCE;
        I3CCSR__I3CBase__INTR_FORCE__HC_ERR_CMD_SEQ_TIMEOUT_FORCE__out_t HC_ERR_CMD_SEQ_TIMEOUT_FORCE;
        I3CCSR__I3CBase__INTR_FORCE__SCHED_CMD_MISSED_TICK_FORCE__out_t SCHED_CMD_MISSED_TICK_FORCE;
    } I3CCSR__I3CBase__INTR_FORCE__out_t;

    typedef struct {
        logic [4:0] value;
    } I3CCSR__I3CBase__DCT_SECTION_OFFSET__TABLE_INDEX__out_t;

    typedef struct {
        I3CCSR__I3CBase__DCT_SECTION_OFFSET__TABLE_INDEX__out_t TABLE_INDEX;
    } I3CCSR__I3CBase__DCT_SECTION_OFFSET__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_HJ_REJECTED__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_CRR_REJECTED__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_IBI_REJECTED__out_t;

    typedef struct {
        I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_HJ_REJECTED__out_t NOTIFY_HJ_REJECTED;
        I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_CRR_REJECTED__out_t NOTIFY_CRR_REJECTED;
        I3CCSR__I3CBase__IBI_NOTIFY_CTRL__NOTIFY_IBI_REJECTED__out_t NOTIFY_IBI_REJECTED;
    } I3CCSR__I3CBase__IBI_NOTIFY_CTRL__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__MATCH_IBI_ID__out_t;

    typedef struct {
        logic [1:0] value;
    } I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__AFTER_N_CHUNKS__out_t;

    typedef struct {
        logic [2:0] value;
    } I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__MATCH_STATUS_TYPE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__IBI_DATA_ABORT_MON__out_t;

    typedef struct {
        I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__MATCH_IBI_ID__out_t MATCH_IBI_ID;
        I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__AFTER_N_CHUNKS__out_t AFTER_N_CHUNKS;
        I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__MATCH_STATUS_TYPE__out_t MATCH_STATUS_TYPE;
        I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__IBI_DATA_ABORT_MON__out_t IBI_DATA_ABORT_MON;
    } I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__DEV_CTX_BASE_LO__BASE_LO__out_t;

    typedef struct {
        I3CCSR__I3CBase__DEV_CTX_BASE_LO__BASE_LO__out_t BASE_LO;
    } I3CCSR__I3CBase__DEV_CTX_BASE_LO__out_t;

    typedef struct {
        logic value;
    } I3CCSR__I3CBase__DEV_CTX_BASE_HI__BASE_HI__out_t;

    typedef struct {
        I3CCSR__I3CBase__DEV_CTX_BASE_HI__BASE_HI__out_t BASE_HI;
    } I3CCSR__I3CBase__DEV_CTX_BASE_HI__out_t;

    typedef struct {
        I3CCSR__I3CBase__HC_CONTROL__out_t HC_CONTROL;
        I3CCSR__I3CBase__CONTROLLER_DEVICE_ADDR__out_t CONTROLLER_DEVICE_ADDR;
        I3CCSR__I3CBase__RESET_CONTROL__out_t RESET_CONTROL;
        I3CCSR__I3CBase__INTR_STATUS__out_t INTR_STATUS;
        I3CCSR__I3CBase__INTR_STATUS_ENABLE__out_t INTR_STATUS_ENABLE;
        I3CCSR__I3CBase__INTR_SIGNAL_ENABLE__out_t INTR_SIGNAL_ENABLE;
        I3CCSR__I3CBase__INTR_FORCE__out_t INTR_FORCE;
        I3CCSR__I3CBase__DCT_SECTION_OFFSET__out_t DCT_SECTION_OFFSET;
        I3CCSR__I3CBase__IBI_NOTIFY_CTRL__out_t IBI_NOTIFY_CTRL;
        I3CCSR__I3CBase__IBI_DATA_ABORT_CTRL__out_t IBI_DATA_ABORT_CTRL;
        I3CCSR__I3CBase__DEV_CTX_BASE_LO__out_t DEV_CTX_BASE_LO;
        I3CCSR__I3CBase__DEV_CTX_BASE_HI__out_t DEV_CTX_BASE_HI;
    } I3CCSR__I3CBase__out_t;

    typedef struct packed {
        logic COMMAND_DATA;
        logic [30:0] _reserved_31_1;
    } I3CCSR__PIOControl__COMMAND_PORT__fields__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
        I3CCSR__PIOControl__COMMAND_PORT__fields__out_t wr_data;
        I3CCSR__PIOControl__COMMAND_PORT__fields__out_t wr_biten;
    } I3CCSR__PIOControl__COMMAND_PORT__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } I3CCSR__PIOControl__RESPONSE_PORT__out_t;

    typedef struct packed {
        logic [31:0] TX_DATA;
    } I3CCSR__PIOControl__XFER_DATA_PORT__fields__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
        I3CCSR__PIOControl__XFER_DATA_PORT__fields__out_t wr_data;
        I3CCSR__PIOControl__XFER_DATA_PORT__fields__out_t wr_biten;
    } I3CCSR__PIOControl__XFER_DATA_PORT__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } I3CCSR__PIOControl__IBI_PORT__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__PIOControl__QUEUE_THLD_CTRL__CMD_EMPTY_BUF_THLD__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__PIOControl__QUEUE_THLD_CTRL__RESP_BUF_THLD__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__PIOControl__QUEUE_THLD_CTRL__IBI_DATA_SEGMENT_SIZE__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__PIOControl__QUEUE_THLD_CTRL__IBI_STATUS_THLD__out_t;

    typedef struct {
        I3CCSR__PIOControl__QUEUE_THLD_CTRL__CMD_EMPTY_BUF_THLD__out_t CMD_EMPTY_BUF_THLD;
        I3CCSR__PIOControl__QUEUE_THLD_CTRL__RESP_BUF_THLD__out_t RESP_BUF_THLD;
        I3CCSR__PIOControl__QUEUE_THLD_CTRL__IBI_DATA_SEGMENT_SIZE__out_t IBI_DATA_SEGMENT_SIZE;
        I3CCSR__PIOControl__QUEUE_THLD_CTRL__IBI_STATUS_THLD__out_t IBI_STATUS_THLD;
    } I3CCSR__PIOControl__QUEUE_THLD_CTRL__out_t;

    typedef struct {
        logic [2:0] value;
    } I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__TX_BUF_THLD__out_t;

    typedef struct {
        logic [2:0] value;
    } I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__RX_BUF_THLD__out_t;

    typedef struct {
        logic [2:0] value;
    } I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__TX_START_THLD__out_t;

    typedef struct {
        logic [2:0] value;
    } I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__RX_START_THLD__out_t;

    typedef struct {
        I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__TX_BUF_THLD__out_t TX_BUF_THLD;
        I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__RX_BUF_THLD__out_t RX_BUF_THLD;
        I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__TX_START_THLD__out_t TX_START_THLD;
        I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__RX_START_THLD__out_t RX_START_THLD;
    } I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__out_t;

    typedef struct {
        logic intr;
    } I3CCSR__PIOControl__PIO_INTR_STATUS__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_INTR_FORCE__TX_THLD_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_INTR_FORCE__RX_THLD_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_INTR_FORCE__IBI_THLD_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_INTR_FORCE__CMD_QUEUE_READY_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_INTR_FORCE__RESP_READY_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_INTR_FORCE__TRANSFER_ABORT_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_INTR_FORCE__TRANSFER_ERR_FORCE__out_t;

    typedef struct {
        I3CCSR__PIOControl__PIO_INTR_FORCE__TX_THLD_FORCE__out_t TX_THLD_FORCE;
        I3CCSR__PIOControl__PIO_INTR_FORCE__RX_THLD_FORCE__out_t RX_THLD_FORCE;
        I3CCSR__PIOControl__PIO_INTR_FORCE__IBI_THLD_FORCE__out_t IBI_THLD_FORCE;
        I3CCSR__PIOControl__PIO_INTR_FORCE__CMD_QUEUE_READY_FORCE__out_t CMD_QUEUE_READY_FORCE;
        I3CCSR__PIOControl__PIO_INTR_FORCE__RESP_READY_FORCE__out_t RESP_READY_FORCE;
        I3CCSR__PIOControl__PIO_INTR_FORCE__TRANSFER_ABORT_FORCE__out_t TRANSFER_ABORT_FORCE;
        I3CCSR__PIOControl__PIO_INTR_FORCE__TRANSFER_ERR_FORCE__out_t TRANSFER_ERR_FORCE;
    } I3CCSR__PIOControl__PIO_INTR_FORCE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_CONTROL__ENABLE__out_t;

    typedef struct {
        logic value;
    } I3CCSR__PIOControl__PIO_CONTROL__ABORT__out_t;

    typedef struct {
        I3CCSR__PIOControl__PIO_CONTROL__ENABLE__out_t ENABLE;
        I3CCSR__PIOControl__PIO_CONTROL__ABORT__out_t ABORT;
    } I3CCSR__PIOControl__PIO_CONTROL__out_t;

    typedef struct {
        I3CCSR__PIOControl__COMMAND_PORT__out_t COMMAND_PORT;
        I3CCSR__PIOControl__RESPONSE_PORT__out_t RESPONSE_PORT;
        I3CCSR__PIOControl__XFER_DATA_PORT__out_t XFER_DATA_PORT;
        I3CCSR__PIOControl__IBI_PORT__out_t IBI_PORT;
        I3CCSR__PIOControl__QUEUE_THLD_CTRL__out_t QUEUE_THLD_CTRL;
        I3CCSR__PIOControl__DATA_BUFFER_THLD_CTRL__out_t DATA_BUFFER_THLD_CTRL;
        I3CCSR__PIOControl__PIO_INTR_STATUS__out_t PIO_INTR_STATUS;
        I3CCSR__PIOControl__PIO_INTR_FORCE__out_t PIO_INTR_FORCE;
        I3CCSR__PIOControl__PIO_CONTROL__out_t PIO_CONTROL;
    } I3CCSR__PIOControl__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__EXTCAP_HEADER__CAP_ID__out_t;

    typedef struct {
        logic [15:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__EXTCAP_HEADER__CAP_LENGTH__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__EXTCAP_HEADER__CAP_ID__out_t CAP_ID;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__EXTCAP_HEADER__CAP_LENGTH__out_t CAP_LENGTH;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__EXTCAP_HEADER__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_0__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_0__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_0__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_1__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_1__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_1__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_2__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_2__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_2__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_3__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_3__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_3__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_0__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_0__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_0__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_1__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_1__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_1__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_2__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_2__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_2__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_3__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_3__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_3__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_4__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_4__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_4__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_5__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_5__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_5__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_6__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_6__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_6__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_STATUS_0__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_STATUS_0__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_STATUS_0__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_STATUS_1__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_STATUS_1__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_STATUS_1__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_RESET__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_RESET__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_RESET__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__RECOVERY_CTRL__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__RECOVERY_CTRL__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__RECOVERY_CTRL__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__RECOVERY_STATUS__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__RECOVERY_STATUS__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__RECOVERY_STATUS__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__HW_STATUS__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__HW_STATUS__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__HW_STATUS__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_CTRL_0__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_CTRL_0__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_CTRL_0__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_CTRL_1__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_CTRL_1__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_CTRL_1__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_0__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_0__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_0__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_1__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_1__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_1__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_2__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_2__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_2__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_3__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_3__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_3__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_4__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_4__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_4__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_5__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_5__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_5__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_DATA__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_DATA__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_DATA__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__EXTCAP_HEADER__out_t EXTCAP_HEADER;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_0__out_t PROT_CAP_0;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_1__out_t PROT_CAP_1;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_2__out_t PROT_CAP_2;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__PROT_CAP_3__out_t PROT_CAP_3;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_0__out_t DEVICE_ID_0;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_1__out_t DEVICE_ID_1;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_2__out_t DEVICE_ID_2;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_3__out_t DEVICE_ID_3;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_4__out_t DEVICE_ID_4;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_5__out_t DEVICE_ID_5;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_ID_6__out_t DEVICE_ID_6;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_STATUS_0__out_t DEVICE_STATUS_0;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_STATUS_1__out_t DEVICE_STATUS_1;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__DEVICE_RESET__out_t DEVICE_RESET;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__RECOVERY_CTRL__out_t RECOVERY_CTRL;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__RECOVERY_STATUS__out_t RECOVERY_STATUS;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__HW_STATUS__out_t HW_STATUS;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_CTRL_0__out_t INDIRECT_FIFO_CTRL_0;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_CTRL_1__out_t INDIRECT_FIFO_CTRL_1;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_0__out_t INDIRECT_FIFO_STATUS_0;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_1__out_t INDIRECT_FIFO_STATUS_1;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_2__out_t INDIRECT_FIFO_STATUS_2;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_3__out_t INDIRECT_FIFO_STATUS_3;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_4__out_t INDIRECT_FIFO_STATUS_4;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_STATUS_5__out_t INDIRECT_FIFO_STATUS_5;
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__INDIRECT_FIFO_DATA__out_t INDIRECT_FIFO_DATA;
    } I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__EXTCAP_HEADER__CAP_ID__out_t;

    typedef struct {
        logic [15:0] value;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__EXTCAP_HEADER__CAP_LENGTH__out_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__EXTCAP_HEADER__CAP_ID__out_t CAP_ID;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__EXTCAP_HEADER__CAP_LENGTH__out_t CAP_LENGTH;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__EXTCAP_HEADER__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_CONTROL__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_CONTROL__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_CONTROL__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_STATUS__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_STATUS__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_STATUS__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_STATUS__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_STATUS__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_STATUS__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_ENABLE__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_ENABLE__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_ENABLE__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_FORCE__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_FORCE__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_FORCE__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_RX_DESCRIPTOR_QUEUE_PORT__TTI_RX_DESCRIPTOR__out_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_RX_DESCRIPTOR_QUEUE_PORT__TTI_RX_DESCRIPTOR__out_t TTI_RX_DESCRIPTOR;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_RX_DESCRIPTOR_QUEUE_PORT__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_RX_DATA_PORT__TTI_RX_DATA__out_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_RX_DATA_PORT__TTI_RX_DATA__out_t TTI_RX_DATA;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_RX_DATA_PORT__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_TX_DESCRIPTOR_QUEUE_PORT__TTI_TX_DESCRIPTOR__out_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_TX_DESCRIPTOR_QUEUE_PORT__TTI_TX_DESCRIPTOR__out_t TTI_TX_DESCRIPTOR;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_TX_DESCRIPTOR_QUEUE_PORT__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_TX_DATA_PORT__TTI_TX_DATA__out_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_TX_DATA_PORT__TTI_TX_DATA__out_t TTI_TX_DATA;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_TX_DATA_PORT__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_QUEUE_THRESHOLD_CONTROL__TTI_RX_DESCRIPTOR_THLD__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_QUEUE_THRESHOLD_CONTROL__TTI_TX_DESCRIPTOR_THLD__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_QUEUE_THRESHOLD_CONTROL__TTI_RX_DATA_THLD__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_QUEUE_THRESHOLD_CONTROL__TTI_TX_DATA_THLD__out_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_QUEUE_THRESHOLD_CONTROL__TTI_RX_DESCRIPTOR_THLD__out_t TTI_RX_DESCRIPTOR_THLD;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_QUEUE_THRESHOLD_CONTROL__TTI_TX_DESCRIPTOR_THLD__out_t TTI_TX_DESCRIPTOR_THLD;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_QUEUE_THRESHOLD_CONTROL__TTI_RX_DATA_THLD__out_t TTI_RX_DATA_THLD;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_QUEUE_THRESHOLD_CONTROL__TTI_TX_DATA_THLD__out_t TTI_TX_DATA_THLD;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_QUEUE_THRESHOLD_CONTROL__out_t;

    typedef struct {
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__EXTCAP_HEADER__out_t EXTCAP_HEADER;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_CONTROL__out_t TTI_CONTROL;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_STATUS__out_t TTI_STATUS;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_STATUS__out_t TTI_INTERRUPT_STATUS;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_ENABLE__out_t TTI_INTERRUPT_ENABLE;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_INTERRUPT_FORCE__out_t TTI_INTERRUPT_FORCE;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_RX_DESCRIPTOR_QUEUE_PORT__out_t TTI_RX_DESCRIPTOR_QUEUE_PORT;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_RX_DATA_PORT__out_t TTI_RX_DATA_PORT;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_TX_DESCRIPTOR_QUEUE_PORT__out_t TTI_TX_DESCRIPTOR_QUEUE_PORT;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_TX_DATA_PORT__out_t TTI_TX_DATA_PORT;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__TTI_QUEUE_THRESHOLD_CONTROL__out_t TTI_QUEUE_THRESHOLD_CONTROL;
    } I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__EXTCAP_HEADER__CAP_ID__out_t;

    typedef struct {
        logic [15:0] value;
    } I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__EXTCAP_HEADER__CAP_LENGTH__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__EXTCAP_HEADER__CAP_ID__out_t CAP_ID;
        I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__EXTCAP_HEADER__CAP_LENGTH__out_t CAP_LENGTH;
    } I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__EXTCAP_HEADER__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__PLACE_HOLDER_1__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__PLACE_HOLDER_1__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__PLACE_HOLDER_1__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__EXTCAP_HEADER__out_t EXTCAP_HEADER;
        I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__PLACE_HOLDER_1__out_t PLACE_HOLDER_1;
    } I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__out_t;

    typedef struct {
        logic [7:0] value;
    } I3CCSR__I3C_EC__ControllerConfigRegisters__EXTCAP_HEADER__CAP_ID__out_t;

    typedef struct {
        logic [15:0] value;
    } I3CCSR__I3C_EC__ControllerConfigRegisters__EXTCAP_HEADER__CAP_LENGTH__out_t;

    typedef struct {
        I3CCSR__I3C_EC__ControllerConfigRegisters__EXTCAP_HEADER__CAP_ID__out_t CAP_ID;
        I3CCSR__I3C_EC__ControllerConfigRegisters__EXTCAP_HEADER__CAP_LENGTH__out_t CAP_LENGTH;
    } I3CCSR__I3C_EC__ControllerConfigRegisters__EXTCAP_HEADER__out_t;

    typedef struct {
        logic [31:0] value;
    } I3CCSR__I3C_EC__ControllerConfigRegisters__PLACE_HOLDER_1__PLACEHOLDER__out_t;

    typedef struct {
        I3CCSR__I3C_EC__ControllerConfigRegisters__PLACE_HOLDER_1__PLACEHOLDER__out_t PLACEHOLDER;
    } I3CCSR__I3C_EC__ControllerConfigRegisters__PLACE_HOLDER_1__out_t;

    typedef struct {
        I3CCSR__I3C_EC__ControllerConfigRegisters__EXTCAP_HEADER__out_t EXTCAP_HEADER;
        I3CCSR__I3C_EC__ControllerConfigRegisters__PLACE_HOLDER_1__out_t PLACE_HOLDER_1;
    } I3CCSR__I3C_EC__ControllerConfigRegisters__out_t;

    typedef struct {
        I3CCSR__I3C_EC__SecureFirmwareRecoveryInterfaceRegisters__out_t SecureFirmwareRecoveryInterfaceRegisters;
        I3CCSR__I3C_EC__TargetTransactionInterfaceRegisters__out_t TargetTransactionInterfaceRegisters;
        I3CCSR__I3C_EC__SoCManagementInterfaceRegisters__out_t SoCManagementInterfaceRegisters;
        I3CCSR__I3C_EC__ControllerConfigRegisters__out_t ControllerConfigRegisters;
    } I3CCSR__I3C_EC__out_t;

    typedef struct {
        logic req;
        logic [9:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } I3CCSR__DAT__out_t;

    typedef struct {
        logic req;
        logic [10:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } I3CCSR__DCT__out_t;

    typedef struct {
        I3CCSR__I3CBase__out_t I3CBase;
        I3CCSR__PIOControl__out_t PIOControl;
        I3CCSR__I3C_EC__out_t I3C_EC;
        I3CCSR__DAT__out_t DAT;
        I3CCSR__DCT__out_t DCT;
    } I3CCSR__out_t;
endpackage
