// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package I3CCSR_pkg;

    localparam I3CCSR_DATA_WIDTH = 32;
    localparam I3CCSR_MIN_ADDR_WIDTH = 12;

    typedef struct {
        logic next;
        logic we;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__resume__in_t;

    typedef struct {
        logic next;
        logic we;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__bus_enable__in_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__resume__in_t resume;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__bus_enable__in_t bus_enable;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__in_t;

    typedef struct {
        logic [6:0] next;
        logic we;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__CONTROLLER_DEVICE_ADDR__dynamic_addr__in_t;

    typedef struct {
        logic next;
        logic we;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__CONTROLLER_DEVICE_ADDR__dynamic_addr_valid__in_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__CONTROLLER_DEVICE_ADDR__dynamic_addr__in_t dynamic_addr;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__CONTROLLER_DEVICE_ADDR__dynamic_addr_valid__in_t dynamic_addr_valid;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__CONTROLLER_DEVICE_ADDR__in_t;

    typedef struct {
        logic next;
        logic we;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__soft_rst__in_t;

    typedef struct {
        logic next;
        logic we;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__cmd_queue__in_t;

    typedef struct {
        logic next;
        logic we;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__resp_queue__in_t;

    typedef struct {
        logic next;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__tx_fifo__in_t;

    typedef struct {
        logic next;
        logic we;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__rx_fifo__in_t;

    typedef struct {
        logic next;
        logic we;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__ibi_queue__in_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__soft_rst__in_t soft_rst;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__cmd_queue__in_t cmd_queue;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__resp_queue__in_t resp_queue;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__tx_fifo__in_t tx_fifo;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__rx_fifo__in_t rx_fifo;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__ibi_queue__in_t ibi_queue;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__in_t;

    typedef struct {
        logic next;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__PRESENT_STATE__ac_current_own__in_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__PRESENT_STATE__ac_current_own__in_t ac_current_own;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__PRESENT_STATE__in_t;

    typedef struct {
        logic next;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_hc_err_cmd_seq_timeout_ea536830_hc_internal_err_45c335fd_hc_seq_cancel_stat_a08fdae1_hc_warn_cmd_seq_stall_76610f5c_sched_cmd_missed_tick_99e0a9cf__hc_internal_err_enable_aede937e_we_f795efe8__in_t;

    typedef struct {
        logic next;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_hc_err_cmd_seq_timeout_ea536830_hc_internal_err_45c335fd_hc_seq_cancel_stat_a08fdae1_hc_warn_cmd_seq_stall_76610f5c_sched_cmd_missed_tick_99e0a9cf__hc_seq_cancel_stat_enable_3de25d4d_we_7b39c9e5__in_t;

    typedef struct {
        logic next;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_hc_err_cmd_seq_timeout_ea536830_hc_internal_err_45c335fd_hc_seq_cancel_stat_a08fdae1_hc_warn_cmd_seq_stall_76610f5c_sched_cmd_missed_tick_99e0a9cf__hc_warn_cmd_seq_stall_enable_8ba75b16_we_aa05b863__in_t;

    typedef struct {
        logic next;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_hc_err_cmd_seq_timeout_ea536830_hc_internal_err_45c335fd_hc_seq_cancel_stat_a08fdae1_hc_warn_cmd_seq_stall_76610f5c_sched_cmd_missed_tick_99e0a9cf__hc_err_cmd_seq_timeout_enable_f09bcece_we_4917f16d__in_t;

    typedef struct {
        logic next;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_hc_err_cmd_seq_timeout_ea536830_hc_internal_err_45c335fd_hc_seq_cancel_stat_a08fdae1_hc_warn_cmd_seq_stall_76610f5c_sched_cmd_missed_tick_99e0a9cf__sched_cmd_missed_tick_enable_c48309e8_we_c19d1151__in_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_hc_err_cmd_seq_timeout_ea536830_hc_internal_err_45c335fd_hc_seq_cancel_stat_a08fdae1_hc_warn_cmd_seq_stall_76610f5c_sched_cmd_missed_tick_99e0a9cf__hc_internal_err_enable_aede937e_we_f795efe8__in_t hc_internal_err;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_hc_err_cmd_seq_timeout_ea536830_hc_internal_err_45c335fd_hc_seq_cancel_stat_a08fdae1_hc_warn_cmd_seq_stall_76610f5c_sched_cmd_missed_tick_99e0a9cf__hc_seq_cancel_stat_enable_3de25d4d_we_7b39c9e5__in_t hc_seq_cancel_stat;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_hc_err_cmd_seq_timeout_ea536830_hc_internal_err_45c335fd_hc_seq_cancel_stat_a08fdae1_hc_warn_cmd_seq_stall_76610f5c_sched_cmd_missed_tick_99e0a9cf__hc_warn_cmd_seq_stall_enable_8ba75b16_we_aa05b863__in_t hc_warn_cmd_seq_stall;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_hc_err_cmd_seq_timeout_ea536830_hc_internal_err_45c335fd_hc_seq_cancel_stat_a08fdae1_hc_warn_cmd_seq_stall_76610f5c_sched_cmd_missed_tick_99e0a9cf__hc_err_cmd_seq_timeout_enable_f09bcece_we_4917f16d__in_t hc_err_cmd_seq_timeout;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_hc_err_cmd_seq_timeout_ea536830_hc_internal_err_45c335fd_hc_seq_cancel_stat_a08fdae1_hc_warn_cmd_seq_stall_76610f5c_sched_cmd_missed_tick_99e0a9cf__sched_cmd_missed_tick_enable_c48309e8_we_c19d1151__in_t sched_cmd_missed_tick;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_hc_err_cmd_seq_timeout_ea536830_hc_internal_err_45c335fd_hc_seq_cancel_stat_a08fdae1_hc_warn_cmd_seq_stall_76610f5c_sched_cmd_missed_tick_99e0a9cf__in_t;

    typedef struct {
        logic [4:0] next;
        logic we;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__DCT_SECTION_OFFSET__table_idx__in_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__DCT_SECTION_OFFSET__table_idx__in_t table_idx;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__DCT_SECTION_OFFSET__in_t;

    typedef struct {
        logic next;
        logic we;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_DATA_ABORT_CTRL__data_abort_monitor__in_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_DATA_ABORT_CTRL__data_abort_monitor__in_t data_abort_monitor;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_DATA_ABORT_CTRL__in_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__in_t HC_CONTROL;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__CONTROLLER_DEVICE_ADDR__in_t CONTROLLER_DEVICE_ADDR;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__in_t RESET_CONTROL;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__PRESENT_STATE__in_t PRESENT_STATE;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_hc_err_cmd_seq_timeout_ea536830_hc_internal_err_45c335fd_hc_seq_cancel_stat_a08fdae1_hc_warn_cmd_seq_stall_76610f5c_sched_cmd_missed_tick_99e0a9cf__in_t INTR_STATUS;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__DCT_SECTION_OFFSET__in_t DCT_SECTION_OFFSET;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_DATA_ABORT_CTRL__in_t IBI_DATA_ABORT_CTRL;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__in_t;

    typedef struct {
        logic wr_ack;
    } PIORegs__COMMAND_PORT__external__in_t;

    typedef struct packed {
        logic resp;
        logic [30:0] _reserved_31_1;
    } PIORegs__RESPONSE_PORT__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        PIORegs__RESPONSE_PORT__external__fields__in_t rd_data;
    } PIORegs__RESPONSE_PORT__external__in_t;

    typedef struct packed {
        logic [31:0] rx_data;
    } PIORegs__XFER_DATA_PORT__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        PIORegs__XFER_DATA_PORT__external__fields__in_t rd_data;
        logic wr_ack;
    } PIORegs__XFER_DATA_PORT__external__in_t;

    typedef struct packed {
        logic ibi_port;
        logic [30:0] _reserved_31_1;
    } PIORegs__IBI_PORT__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        PIORegs__IBI_PORT__external__fields__in_t rd_data;
    } PIORegs__IBI_PORT__external__in_t;

    typedef struct {
        logic next;
    } PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__tx_threshold_enable_ed06f19c_we_1830bfcc__in_t;

    typedef struct {
        logic next;
    } PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__rx_threshold_enable_b77e95de_we_dc1ba1c1__in_t;

    typedef struct {
        logic next;
    } PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__ibi_status_enable_601f9960_we_45cb7237__in_t;

    typedef struct {
        logic next;
    } PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__cmd_queue_ready_enable_fed9dff3_we_3996d726__in_t;

    typedef struct {
        logic next;
    } PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__resp_ready_enable_661b4b23_we_17d6325c__in_t;

    typedef struct {
        logic next;
    } PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__transfer_abort_enable_34bdf8f6_we_775bb50a__in_t;

    typedef struct {
        logic next;
    } PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__transfer_err_enable_1697fc61_we_77e72d66__in_t;

    typedef struct {
        PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__tx_threshold_enable_ed06f19c_we_1830bfcc__in_t tx_threshold;
        PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__rx_threshold_enable_b77e95de_we_dc1ba1c1__in_t rx_threshold;
        PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__ibi_status_enable_601f9960_we_45cb7237__in_t ibi_status;
        PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__cmd_queue_ready_enable_fed9dff3_we_3996d726__in_t cmd_queue_ready;
        PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__resp_ready_enable_661b4b23_we_17d6325c__in_t resp_ready;
        PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__transfer_abort_enable_34bdf8f6_we_775bb50a__in_t transfer_abort;
        PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__transfer_err_enable_1697fc61_we_77e72d66__in_t transfer_err;
    } PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__in_t;

    typedef struct {
        logic next;
        logic we;
    } PIORegs__PIO_CONTROL__rs_req__in_t;

    typedef struct {
        PIORegs__PIO_CONTROL__rs_req__in_t rs_req;
    } PIORegs__PIO_CONTROL__in_t;

    typedef struct {
        PIORegs__COMMAND_PORT__external__in_t COMMAND_PORT;
        PIORegs__RESPONSE_PORT__external__in_t RESPONSE_PORT;
        PIORegs__XFER_DATA_PORT__external__in_t XFER_DATA_PORT;
        PIORegs__IBI_PORT__external__in_t IBI_PORT;
        PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__in_t PIO_INTR_STATUS;
        PIORegs__PIO_CONTROL__in_t PIO_CONTROL;
    } PIORegs__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } I3CCSR__DAT__external__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } I3CCSR__DCT__external__in_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__in_t I3CBase;
        PIORegs__in_t PIOControl;
        I3CCSR__DAT__external__in_t DAT;
        I3CCSR__DCT__external__in_t DCT;
    } I3CCSR__in_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__iba_include__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__i2c_devs__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__hot_join__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__halt_on_cmd_seq_timeout__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__abort__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__resume__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__bus_enable__out_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__iba_include__out_t iba_include;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__i2c_devs__out_t i2c_devs;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__hot_join__out_t hot_join;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__halt_on_cmd_seq_timeout__out_t halt_on_cmd_seq_timeout;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__abort__out_t abort;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__resume__out_t resume;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__bus_enable__out_t bus_enable;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__out_t;

    typedef struct {
        logic [6:0] value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__CONTROLLER_DEVICE_ADDR__dynamic_addr__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__CONTROLLER_DEVICE_ADDR__dynamic_addr_valid__out_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__CONTROLLER_DEVICE_ADDR__dynamic_addr__out_t dynamic_addr;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__CONTROLLER_DEVICE_ADDR__dynamic_addr_valid__out_t dynamic_addr_valid;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__CONTROLLER_DEVICE_ADDR__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__soft_rst__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__cmd_queue__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__resp_queue__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__tx_fifo__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__rx_fifo__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__ibi_queue__out_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__soft_rst__out_t soft_rst;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__cmd_queue__out_t cmd_queue;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__resp_queue__out_t resp_queue;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__tx_fifo__out_t tx_fifo;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__rx_fifo__out_t rx_fifo;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__ibi_queue__out_t ibi_queue;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__out_t;

    typedef struct {
        logic intr;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_hc_err_cmd_seq_timeout_ea536830_hc_internal_err_45c335fd_hc_seq_cancel_stat_a08fdae1_hc_warn_cmd_seq_stall_76610f5c_sched_cmd_missed_tick_99e0a9cf__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_ENABLE__hc_internal_err_en__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_ENABLE__hc_seq_cancel_stat_en__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_ENABLE__hc_warn_cmd_seq_stall_en__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_ENABLE__hc_err_cmd_seq_timeout_en__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_ENABLE__sched_cmd_missed_tick_en__out_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_ENABLE__hc_internal_err_en__out_t hc_internal_err_en;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_ENABLE__hc_seq_cancel_stat_en__out_t hc_seq_cancel_stat_en;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_ENABLE__hc_warn_cmd_seq_stall_en__out_t hc_warn_cmd_seq_stall_en;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_ENABLE__hc_err_cmd_seq_timeout_en__out_t hc_err_cmd_seq_timeout_en;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_ENABLE__sched_cmd_missed_tick_en__out_t sched_cmd_missed_tick_en;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_ENABLE__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_SIGNAL_ENABLE__hc_internal_err_intr_en__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_SIGNAL_ENABLE__hc_seq_cancel_stat_intr_en__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_SIGNAL_ENABLE__hc_warn_cmd_seq_stall_intr_en__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_SIGNAL_ENABLE__hc_err_cmd_seq_timeout_intr_en__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_SIGNAL_ENABLE__sched_cmd_missed_tick_intr_en__out_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_SIGNAL_ENABLE__hc_internal_err_intr_en__out_t hc_internal_err_intr_en;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_SIGNAL_ENABLE__hc_seq_cancel_stat_intr_en__out_t hc_seq_cancel_stat_intr_en;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_SIGNAL_ENABLE__hc_warn_cmd_seq_stall_intr_en__out_t hc_warn_cmd_seq_stall_intr_en;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_SIGNAL_ENABLE__hc_err_cmd_seq_timeout_intr_en__out_t hc_err_cmd_seq_timeout_intr_en;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_SIGNAL_ENABLE__sched_cmd_missed_tick_intr_en__out_t sched_cmd_missed_tick_intr_en;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_SIGNAL_ENABLE__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_FORCE__force_hc_internal_err__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_FORCE__force_hc_seq_cancel_stat__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_FORCE__force_hc_warn_cmd_seq_stall__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_FORCE__force_hc_err_cmd_seq_timeout__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_FORCE__force_sched_cmd_missed_tick__out_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_FORCE__force_hc_internal_err__out_t force_hc_internal_err;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_FORCE__force_hc_seq_cancel_stat__out_t force_hc_seq_cancel_stat;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_FORCE__force_hc_warn_cmd_seq_stall__out_t force_hc_warn_cmd_seq_stall;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_FORCE__force_hc_err_cmd_seq_timeout__out_t force_hc_err_cmd_seq_timeout;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_FORCE__force_sched_cmd_missed_tick__out_t force_sched_cmd_missed_tick;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_FORCE__out_t;

    typedef struct {
        logic [4:0] value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__DCT_SECTION_OFFSET__table_idx__out_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__DCT_SECTION_OFFSET__table_idx__out_t table_idx;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__DCT_SECTION_OFFSET__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_NOTIFY_CTRL__hj_rejected__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_NOTIFY_CTRL__crr_rejected__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_NOTIFY_CTRL__ibi_rejected__out_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_NOTIFY_CTRL__hj_rejected__out_t hj_rejected;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_NOTIFY_CTRL__crr_rejected__out_t crr_rejected;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_NOTIFY_CTRL__ibi_rejected__out_t ibi_rejected;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_NOTIFY_CTRL__out_t;

    typedef struct {
        logic [7:0] value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_DATA_ABORT_CTRL__match_id__out_t;

    typedef struct {
        logic [1:0] value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_DATA_ABORT_CTRL__max_data_length__out_t;

    typedef struct {
        logic [2:0] value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_DATA_ABORT_CTRL__ibi_match_statsus__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_DATA_ABORT_CTRL__data_abort_monitor__out_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_DATA_ABORT_CTRL__match_id__out_t match_id;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_DATA_ABORT_CTRL__max_data_length__out_t max_data_length;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_DATA_ABORT_CTRL__ibi_match_statsus__out_t ibi_match_statsus;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_DATA_ABORT_CTRL__data_abort_monitor__out_t data_abort_monitor;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_DATA_ABORT_CTRL__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__DEV_CTX_BASE_LO__base_lo__out_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__DEV_CTX_BASE_LO__base_lo__out_t base_lo;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__DEV_CTX_BASE_LO__out_t;

    typedef struct {
        logic value;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__DEV_CTX_BASE_HI__base_hi__out_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__DEV_CTX_BASE_HI__base_hi__out_t base_hi;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__DEV_CTX_BASE_HI__out_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__HC_CONTROL__out_t HC_CONTROL;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__CONTROLLER_DEVICE_ADDR__out_t CONTROLLER_DEVICE_ADDR;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__RESET_CONTROL__out_t RESET_CONTROL;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_hc_err_cmd_seq_timeout_ea536830_hc_internal_err_45c335fd_hc_seq_cancel_stat_a08fdae1_hc_warn_cmd_seq_stall_76610f5c_sched_cmd_missed_tick_99e0a9cf__out_t INTR_STATUS;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_STATUS_ENABLE__out_t INTR_STATUS_ENABLE;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_SIGNAL_ENABLE__out_t INTR_SIGNAL_ENABLE;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__INTR_FORCE__out_t INTR_FORCE;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__DCT_SECTION_OFFSET__out_t DCT_SECTION_OFFSET;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_NOTIFY_CTRL__out_t IBI_NOTIFY_CTRL;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__IBI_DATA_ABORT_CTRL__out_t IBI_DATA_ABORT_CTRL;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__DEV_CTX_BASE_LO__out_t DEV_CTX_BASE_LO;
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__DEV_CTX_BASE_HI__out_t DEV_CTX_BASE_HI;
    } BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__out_t;

    typedef struct packed {
        logic cmd;
        logic [30:0] _reserved_31_1;
    } PIORegs__COMMAND_PORT__external__fields__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
        PIORegs__COMMAND_PORT__external__fields__out_t wr_data;
        PIORegs__COMMAND_PORT__external__fields__out_t wr_biten;
    } PIORegs__COMMAND_PORT__external__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } PIORegs__RESPONSE_PORT__external__out_t;

    typedef struct packed {
        logic [31:0] tx_data;
    } PIORegs__XFER_DATA_PORT__external__fields__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
        PIORegs__XFER_DATA_PORT__external__fields__out_t wr_data;
        PIORegs__XFER_DATA_PORT__external__fields__out_t wr_biten;
    } PIORegs__XFER_DATA_PORT__external__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } PIORegs__IBI_PORT__external__out_t;

    typedef struct {
        logic [7:0] value;
    } PIORegs__QUEUE_THLD_CTRL__cmd_empty__out_t;

    typedef struct {
        logic [7:0] value;
    } PIORegs__QUEUE_THLD_CTRL__resp_buf__out_t;

    typedef struct {
        logic [7:0] value;
    } PIORegs__QUEUE_THLD_CTRL__ibi_data_size__out_t;

    typedef struct {
        logic [7:0] value;
    } PIORegs__QUEUE_THLD_CTRL__ibi_status__out_t;

    typedef struct {
        PIORegs__QUEUE_THLD_CTRL__cmd_empty__out_t cmd_empty;
        PIORegs__QUEUE_THLD_CTRL__resp_buf__out_t resp_buf;
        PIORegs__QUEUE_THLD_CTRL__ibi_data_size__out_t ibi_data_size;
        PIORegs__QUEUE_THLD_CTRL__ibi_status__out_t ibi_status;
    } PIORegs__QUEUE_THLD_CTRL__out_t;

    typedef struct {
        logic [2:0] value;
    } PIORegs__DATA_BUFFER_THLD_CTRL__tx_bux__out_t;

    typedef struct {
        logic [2:0] value;
    } PIORegs__DATA_BUFFER_THLD_CTRL__rx_buf__out_t;

    typedef struct {
        logic [2:0] value;
    } PIORegs__DATA_BUFFER_THLD_CTRL__tx_start_log__out_t;

    typedef struct {
        logic [2:0] value;
    } PIORegs__DATA_BUFFER_THLD_CTRL__rx_start_log__out_t;

    typedef struct {
        PIORegs__DATA_BUFFER_THLD_CTRL__tx_bux__out_t tx_bux;
        PIORegs__DATA_BUFFER_THLD_CTRL__rx_buf__out_t rx_buf;
        PIORegs__DATA_BUFFER_THLD_CTRL__tx_start_log__out_t tx_start_log;
        PIORegs__DATA_BUFFER_THLD_CTRL__rx_start_log__out_t rx_start_log;
    } PIORegs__DATA_BUFFER_THLD_CTRL__out_t;

    typedef struct {
        logic intr;
    } PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__out_t;

    typedef struct {
        logic value;
    } PIORegs__PIO_INTR_FORCE__force_tx_threshold__out_t;

    typedef struct {
        logic value;
    } PIORegs__PIO_INTR_FORCE__force_rx_threshold__out_t;

    typedef struct {
        logic value;
    } PIORegs__PIO_INTR_FORCE__force_ibi_status__out_t;

    typedef struct {
        logic value;
    } PIORegs__PIO_INTR_FORCE__force_cmd_queue_ready__out_t;

    typedef struct {
        logic value;
    } PIORegs__PIO_INTR_FORCE__force_resp_ready__out_t;

    typedef struct {
        logic value;
    } PIORegs__PIO_INTR_FORCE__force_transfer_abort__out_t;

    typedef struct {
        logic value;
    } PIORegs__PIO_INTR_FORCE__force_transfer_err__out_t;

    typedef struct {
        PIORegs__PIO_INTR_FORCE__force_tx_threshold__out_t force_tx_threshold;
        PIORegs__PIO_INTR_FORCE__force_rx_threshold__out_t force_rx_threshold;
        PIORegs__PIO_INTR_FORCE__force_ibi_status__out_t force_ibi_status;
        PIORegs__PIO_INTR_FORCE__force_cmd_queue_ready__out_t force_cmd_queue_ready;
        PIORegs__PIO_INTR_FORCE__force_resp_ready__out_t force_resp_ready;
        PIORegs__PIO_INTR_FORCE__force_transfer_abort__out_t force_transfer_abort;
        PIORegs__PIO_INTR_FORCE__force_transfer_err__out_t force_transfer_err;
    } PIORegs__PIO_INTR_FORCE__out_t;

    typedef struct {
        logic value;
    } PIORegs__PIO_CONTROL__enable_req__out_t;

    typedef struct {
        logic value;
    } PIORegs__PIO_CONTROL__abort_req__out_t;

    typedef struct {
        PIORegs__PIO_CONTROL__enable_req__out_t enable_req;
        PIORegs__PIO_CONTROL__abort_req__out_t abort_req;
    } PIORegs__PIO_CONTROL__out_t;

    typedef struct {
        PIORegs__COMMAND_PORT__external__out_t COMMAND_PORT;
        PIORegs__RESPONSE_PORT__external__out_t RESPONSE_PORT;
        PIORegs__XFER_DATA_PORT__external__out_t XFER_DATA_PORT;
        PIORegs__IBI_PORT__external__out_t IBI_PORT;
        PIORegs__QUEUE_THLD_CTRL__out_t QUEUE_THLD_CTRL;
        PIORegs__DATA_BUFFER_THLD_CTRL__out_t DATA_BUFFER_THLD_CTRL;
        PIORegs__PIO_INTR_STATUS_cmd_queue_ready_cf7af7e0_ibi_status_bf071c69_resp_ready_97224b8a_rx_threshold_be90c9fa_transfer_abort_e1bccd1b_transfer_err_7b7b4cb9_tx_threshold_f1e247cd__out_t PIO_INTR_STATUS;
        PIORegs__PIO_INTR_FORCE__out_t PIO_INTR_FORCE;
        PIORegs__PIO_CONTROL__out_t PIO_CONTROL;
    } PIORegs__out_t;

    typedef struct {
        logic req;
        logic [9:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } I3CCSR__DAT__external__out_t;

    typedef struct {
        logic req;
        logic [10:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } I3CCSR__DCT__external__out_t;

    typedef struct {
        BaseRegs_PIO_offset_100_DAT_table_size_7f_DAT_offset_400_DCT_table_size_7f_DCT_offset_800_MIPI_commands_35__out_t I3CBase;
        PIORegs__out_t PIOControl;
        I3CCSR__DAT__external__out_t DAT;
        I3CCSR__DCT__external__out_t DCT;
    } I3CCSR__out_t;
endpackage
