name: Run Tests

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - name: Install dependencies
        run: |
          sudo apt -qqy update
          sudo apt -qqy --no-install-recommends install help2man libfl-dev make g++ git bison flex gperf \
                                                        libreadline-dev libbz2-dev autoconf python3-sphinx \
                                                        python3-docopt

      - name: Setup repository
        uses: actions/checkout@v4

      - name: Get Submodules
        run: |
          git submodule update --init --recursive

      - name: Install Pyenv
        run: |
          ./install.sh

      - name: Build Icarus
        run: |
          git clone https://github.com/steveicarus/iverilog.git
          cd iverilog
          git checkout 06077ed026b4d8498d9129a6acfb0b44d0b51f18
          sh autoconf.sh
          ./configure
          make -j$(nproc)
          sudo make install
          iverilog -V

      - name: Build Verilator
        run: |
          git clone https://github.com/verilator/verilator -b v5.024
          cd verilator
          autoconf
          ./configure
          make -j$(nproc)
          sudo make install
          verilator --version

      - name: Run Tests
        run: |
          make install-uvm
          source activate.sh
          make tests

  another_tests:
    name: Another
    runs-on: [ self-hosted, Linux, X64, gcp-custom-runners ]
    container: centos:8
    env:
      GHA_EXTERNAL_DISK: additional-tools
    steps:
      - name: Install dependencies
        run: |
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
          yum update -y
          yum install -y git tar wget libnsl bc time make gcc gcc-c++ perl python3 python3-pip zlib-devel \
          openssl-devel xz-devel sqlite-devel libffi-devel ncurses-devel bzip2-devel readline-devel

      - name: Setup repository
        uses: actions/checkout@v4

      - name: Get Submodules
        run: git submodule update --init --recursive

      - name: Install Pyenv
        run: ./install.sh

      - name: Run Tests
        run: _secret_run_i3c_tests
